logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy=TRACE:
    ROOT: INFO
    org.springframework.batch: INFO
    tech.jhipster: DEBUG
    org.nmcpye.datarun: DEBUG

spring:
  devtools:
    restart:
      enabled: false
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
      uri: mongodb://dRunUser:dRunUser@localhost:27017/dataRunApi
      auto-index-creation: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/dataRunApiStages
    username: dataRunApi
    password: dataRunApi

    hikari:
      poolName: Hikari
      auto-commit: false
  liquibase:
    contexts: dev
  jooq:
    sql-dialect: postgres
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
server:
  port: 8080
  forward-headers-strategy: native

datarun:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: MjJmNDA2ZjQwMzg5NWE0ZDFiZmZmY2IzYzk2NmQ0MmI4OTM0NWU1MDBjYmU1N2VkYmNjOWM2ZmI2OGVlZWVmYTI0NDM0Y2JhY2ZhMWI2Nzg2ZGY2YWNhZjNmMTViYTcyZTNmMjMwNmFjZTRkMTAzOTVhYjlkNDRhOWZhNDJhY2I=
        #        token-validity-in-seconds: 900 # Token is valid 15 minutes
        token-validity-in-seconds: 86400 # Token is valid 24 hours
        refresh-token-validity-in-seconds: 2592000 # 30 days
        token-validity-in-seconds-for-remember-me: 2592000
        rsa-private-key: >-
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfhlAaCjQe9U7HT+MmzjKoTX8c9ZIEoHpxo7cuZ0YVFR6YW8QYVRG5zsQSeiJbS1c6lgFxZXcKMaGAfHkTXdv9jHJpQYfmlf/j998QR9667x4AtHOZUIue7VRkHmkOMBxa8/yneCOjb9bjQckirs/mxbOBKV1wvG+ko6vjjj4zWQ7aM0m9QZagWTmpE0soUp6zyZ8c5u7QdPUJmXhXRw47Cm72VzrUO4EBYFqEiFRPJdNaDpr1ZZK5Kw/MSSAA7d8cc7C4WeIKqRW2wkuyBOinmv2dD0AkNPn+3JWt2YYmsniXEeES2CSNxda5to+gSicp1H7UidHr41+cDO0MzXmFAgMBAAECggEAB4QsrjiddKxdp8URiiii0pl2kn08zr+aKIeS7ODl0iSts90P0/VFWz1gSxFhINV5O/2JMatOHN2/L86HMxmAvfIW1yaRlvsQIWqMIpHx7yavToL+6iuu4HA4DtDJMpqjg2LFz6tr9nPuRCsh2HxnHe1iKoUYVEsBcaVak7BS9iVT6RhtM/M3v1FURdD9utAbXPcQN2fQZLIkftopQ22x5W+txcH/Vex2yG94f1q7ZYQYmdfwrKQ4G8cjk/QrhJ911wiWxDoDscWljnEIcdt8TaJo3oCak7LZZowvVUftcAo/N5exLAp5E6h47gEsTqpauXjGpS1SNZApTMfwomICkwKBgQDVR2aBUWWHXwM+hB2bSWsmLEOnQbQAnp5xlMJYCKh8zrL0/+Qa2+UVV98n7HFF4IMEzilRr7OQ/8TTtSQmmwYlwQ8xjkumafhyZvIjjCwI5Ig6mgWm0fc4bwvR01JXEDWEYeJTiS02q6oP7AUYzOa/hzaB5+r/FEanZ1OGAoMySwKBgQC/enslsMa0I/ke7AyIFarthrNLILprwrfqDQPAlBR9Lwcd2mF937tMQg+EQLCh21cyXkDiuKJiKJ6nnAk0IMXrNTRYkBIizqpPWwoKrRpYyLFwr9ymYwK2NmNMxdajR+RbDBTAvJePs5H9oUXcnMQQT11au/3XXr+gE8qWV+0hbwKBgAfb9LQJOtONNcJk/e5N+0vRz8BnFGn9bltDHxI9Z3AJ8eBDWbV/quZpcYi4Fsh7aHiR3EXtUpGiSy99+lIN3mEfxx6NXs5IE2ar0npq3OiK+1YlfNXT4OdMeEQIJH2e1EoHjV6ErIzaMI8bpGhwjIQ8SE7rK+awaZYboaFLkGgXAoGBAIKO8xT5+iKuPJj2/nxzub6HkAzz3ejINjricOKIlYfd3w5d7wey27TdflMBAO777fKsDbYJir8/Tx6d6DChABKmjnCsm5EcNUgynSA2c7aB8WsSnnLdI+Y2I3MfmoBu7qeeDzBz5yvWlv7HTilkwtMUKmVJtYV6V1LA6+ujPE8FAoGAO3c7qihHPfZ3lsbyRKiVzH5Rb/xyW4dW6h16ey0MxiINi3YtMws1dnxNFTHRGJB19XBqLjvzZFxpTQG72MID5lT48njuJFapbKfF8vl/a+Qs7dfYg4THQ387lDEiU5x3xevl0RpSMWiNXn9IH6JS12cQriMgQmV9oP6O3rZNIR0=
        rsa-public-key: >-
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn4ZQGgo0HvVOx0/jJs4yqE1/HPWSBKB6caO3LmdGFRUemFvEGFURuc7EEnoiW0tXOpYBcWV3CjGhgHx5E13b/YxyaUGH5pX/4/ffEEfeuu8eALRzmVCLnu1UZB5pDjAcWvP8p3gjo2/W40HJIq7P5sWzgSldcLxvpKOr444+M1kO2jNJvUGWoFk5qRNLKFKes8mfHObu0HT1CZl4V0cOOwpu9lc61DuBAWBahIhUTyXTWg6a9WWSuSsPzEkgAO3fHHOwuFniCqkVtsJLsgTop5r9nQ9AJDT5/tyVrdmGJrJ4lxHhEtgkjcXWubaPoEonKdR+1InR6+NfnAztDM15hQIDAQAB
    client-authorization:
      jwk-set-uri: http://localhost:8080/oauth2/jwks
outbox:
  relay:
    poll-interval-ms: 2000   # polling delay between polls (ms)
    batch-size: 20           # how many to claim per poll
    worker-threads: 8        # number of concurrent worker threads
    max-attempts: 5
    visibility-timeout-seconds: 600   # reclaim if processing_started older than this
    reclaim-interval-ms: 60000
backoff:
  base-seconds: 30
  jitter-seconds: 5
  max-seconds: 3600


pilot:
  repeat:
    uids: RPT_aaf9a7ade8ad8535,RPT_0cb69bd7ed22c6d5
  page:
    size: 500
  run:
    backfill: true
    projection: true

# from mongo, do we run or not, comment all if not
migration:
  mongo:
    collection: data_form_submission
  chunk:
    size: 150
  page:
    size: 100
  run: true


  size: 200
  cron: "0 */1 * * * *"

  submissionUids: Eelt7ZePvz0, LaGeMmmCEtH, QIMwgBqVsqW, zglED4TsbTh, M3fdtzBSpn8, RQlMiMcukid, gGyX1CVnOaw, YLcsWJlB7uy, hcLU8ZtUdSd, Ls9TW9eSlYH, ck2pHW93sk2, rkwH5QNofRn, KcsA3KETRbY, woOl5yAmi8C, BoEmHvJUEpb,W8EtCDYfp1w, MrxGOZ6stwS, UYBPOIfCU0a, mpmjpJcMuas, IP2dMtoJkO4, ONIaOpzoYAe
  runOutboxBackfill: true

jhipster:
  client-app:
    name: "datarun"
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 200 # Number of objects in each cache entry
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200'

    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: MjJmNDA2ZjQwMzg5NWE0ZDFiZmZmY2IzYzk2NmQ0MmI4OTM0NWU1MDBjYmU1N2VkYmNjOWM2ZmI2OGVlZWVmYTI0NDM0Y2JhY2ZhMWI2Nzg2ZGY2YWNhZjNmMTViYTcyZTNmMjMwNmFjZTRkMTAzOTVhYjlkNDRhOWZhNDJhY2I=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400 # Token is valid 24 hours
        #        token-validity-in-seconds: 900 # Token is valid 15 minutes
        token-validity-in-seconds-for-remember-me: 2592000
#    oauth2:
#      audience:
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
