/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.nmcpye.datarun.jooq.DefaultCatalog;
import org.nmcpye.datarun.jooq.public_.tables.AppUser;
import org.nmcpye.datarun.jooq.public_.tables.Assignment;
import org.nmcpye.datarun.jooq.public_.tables.AssignmentMember;
import org.nmcpye.datarun.jooq.public_.tables.AssignmentPartyBinding;
import org.nmcpye.datarun.jooq.public_.tables.OrgUnit;
import org.nmcpye.datarun.jooq.public_.tables.Party;
import org.nmcpye.datarun.jooq.public_.tables.PartySet;
import org.nmcpye.datarun.jooq.public_.tables.PartySetMember;
import org.nmcpye.datarun.jooq.public_.tables.Team;
import org.nmcpye.datarun.jooq.public_.tables.TeamUser;
import org.nmcpye.datarun.jooq.public_.tables.UserAllowedParty;
import org.nmcpye.datarun.jooq.public_.tables.UserGroup;
import org.nmcpye.datarun.jooq.public_.tables.UserGroupUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.app_user</code>.
     */
    public final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.assignment</code>.
     */
    public final Assignment ASSIGNMENT = Assignment.ASSIGNMENT;

    /**
     * The table <code>public.assignment_member</code>.
     */
    public final AssignmentMember ASSIGNMENT_MEMBER = AssignmentMember.ASSIGNMENT_MEMBER;

    /**
     * The table <code>public.assignment_party_binding</code>.
     */
    public final AssignmentPartyBinding ASSIGNMENT_PARTY_BINDING = AssignmentPartyBinding.ASSIGNMENT_PARTY_BINDING;

    /**
     * The table <code>public.org_unit</code>.
     */
    public final OrgUnit ORG_UNIT = OrgUnit.ORG_UNIT;

    /**
     * The table <code>public.party</code>.
     */
    public final Party PARTY = Party.PARTY;

    /**
     * The table <code>public.party_set</code>.
     */
    public final PartySet PARTY_SET = PartySet.PARTY_SET;

    /**
     * The table <code>public.party_set_member</code>.
     */
    public final PartySetMember PARTY_SET_MEMBER = PartySetMember.PARTY_SET_MEMBER;

    /**
     * The table <code>public.team</code>.
     */
    public final Team TEAM = Team.TEAM;

    /**
     * The table <code>public.team_user</code>.
     */
    public final TeamUser TEAM_USER = TeamUser.TEAM_USER;

    /**
     * The table <code>public.user_allowed_party</code>.
     */
    public final UserAllowedParty USER_ALLOWED_PARTY = UserAllowedParty.USER_ALLOWED_PARTY;

    /**
     * The table <code>public.user_group</code>.
     */
    public final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    /**
     * The table <code>public.user_group_users</code>.
     */
    public final UserGroupUsers USER_GROUP_USERS = UserGroupUsers.USER_GROUP_USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AppUser.APP_USER,
            Assignment.ASSIGNMENT,
            AssignmentMember.ASSIGNMENT_MEMBER,
            AssignmentPartyBinding.ASSIGNMENT_PARTY_BINDING,
            OrgUnit.ORG_UNIT,
            Party.PARTY,
            PartySet.PARTY_SET,
            PartySetMember.PARTY_SET_MEMBER,
            Team.TEAM,
            TeamUser.TEAM_USER,
            UserAllowedParty.USER_ALLOWED_PARTY,
            UserGroup.USER_GROUP,
            UserGroupUsers.USER_GROUP_USERS
        );
    }
}
