/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.UserAllowedParty;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAllowedPartyRecord extends UpdatableRecordImpl<UserAllowedPartyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_allowed_party.user_id</code>.
     */
    public void setUserId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_allowed_party.user_id</code>.
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_allowed_party.party_id</code>.
     */
    public void setPartyId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_allowed_party.party_id</code>.
     */
    public UUID getPartyId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.user_allowed_party.permission_mask</code>.
     */
    public void setPermissionMask(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_allowed_party.permission_mask</code>.
     */
    public Integer getPermissionMask() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.user_allowed_party.provenance</code>.
     */
    public void setProvenance(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_allowed_party.provenance</code>.
     */
    public JSONB getProvenance() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.user_allowed_party.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_allowed_party.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAllowedPartyRecord
     */
    public UserAllowedPartyRecord() {
        super(UserAllowedParty.USER_ALLOWED_PARTY);
    }

    /**
     * Create a detached, initialised UserAllowedPartyRecord
     */
    public UserAllowedPartyRecord(String userId, UUID partyId, Integer permissionMask, JSONB provenance, LocalDateTime lastUpdated) {
        super(UserAllowedParty.USER_ALLOWED_PARTY);

        setUserId(userId);
        setPartyId(partyId);
        setPermissionMask(permissionMask);
        setProvenance(provenance);
        setLastUpdated(lastUpdated);
        resetChangedOnNotNull();
    }
}
