package org.nmcpye.datarun.outbox.mapper;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.nmcpye.datarun.outbox.dto.SubmissionPayload;
import org.springframework.stereotype.Component;

/**
 * MapStruct mapper between Outbox entity and OutboxDto.
 * Implementation will be generated by MapStruct at build time.
 * <p>
 * Future: customize mappings for JSON payload -> JsonNode if we change types later.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public abstract class OutboxOutboxPayloadMapper {
    private final ObjectMapper objectMapper;

    public SubmissionPayload toSubmissionPayload(String payload) {
        if (payload == null) return null;
        try {
            JsonNode root = objectMapper.readTree(payload);
            return objectMapper.convertValue(root, SubmissionPayload.class);
        } catch (Exception e) {
            log.warn("Transform: invalid JSON payload for outboxId={} : {}", payload, e.getMessage());
            return null;
        }
    }
}
