package org.nmcpye.datarun.outbox.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;
import org.nmcpye.datarun.outbox.dto.OutboxDto;
import org.nmcpye.datarun.outbox.entity.Outbox;

/**
 * MapStruct mapper between Outbox entity and OutboxDto.
 * Implementation will be generated by MapStruct at build time.
 * <p>
 * Future: customize mappings for JSON payload -> JsonNode if we change types later.
 */
@Mapper
public interface OutboxMapper {
    OutboxMapper INSTANCE = Mappers.getMapper(OutboxMapper.class);
    OutboxDto toDto(Outbox outbox);

    Outbox toEntity(OutboxDto dto);
}
