package org.nmcpye.datarun.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChvSupplyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChvSupplyAllPropertiesEquals(ChvSupply expected, ChvSupply actual) {
        assertChvSupplyAutoGeneratedPropertiesEquals(expected, actual);
        assertChvSupplyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChvSupplyAllUpdatablePropertiesEquals(ChvSupply expected, ChvSupply actual) {
        assertChvSupplyUpdatableFieldsEquals(expected, actual);
        assertChvSupplyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChvSupplyAutoGeneratedPropertiesEquals(ChvSupply expected, ChvSupply actual) {
        assertThat(expected)
            .as("Verify ChvSupply auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChvSupplyUpdatableFieldsEquals(ChvSupply expected, ChvSupply actual) {
        assertThat(expected)
            .as("Verify ChvSupply relevant properties")
            .satisfies(e -> assertThat(e.getUid()).as("check uid").isEqualTo(actual.getUid()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getItem()).as("check item").isEqualTo(actual.getItem()))
            .satisfies(e -> assertThat(e.getPreviousBalance()).as("check previousBalance").isEqualTo(actual.getPreviousBalance()))
            .satisfies(e -> assertThat(e.getNewSupply()).as("check newSupply").isEqualTo(actual.getNewSupply()))
            .satisfies(e -> assertThat(e.getConsumed()).as("check consumed").isEqualTo(actual.getConsumed()))
            .satisfies(e -> assertThat(e.getLostCorrupt()).as("check lostCorrupt").isEqualTo(actual.getLostCorrupt()))
            .satisfies(e -> assertThat(e.getRemaining()).as("check remaining").isEqualTo(actual.getRemaining()))
            .satisfies(e -> assertThat(e.getComment()).as("check comment").isEqualTo(actual.getComment()))
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()))
            .satisfies(e -> assertThat(e.getStartEntryTime()).as("check startEntryTime").isEqualTo(actual.getStartEntryTime()))
            .satisfies(e -> assertThat(e.getFinishedEntryTime()).as("check finishedEntryTime").isEqualTo(actual.getFinishedEntryTime()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChvSupplyUpdatableRelationshipsEquals(ChvSupply expected, ChvSupply actual) {
        assertThat(expected)
            .as("Verify ChvSupply relationships")
            .satisfies(e -> assertThat(e.getActivity()).as("check activity").isEqualTo(actual.getActivity()))
            .satisfies(e -> assertThat(e.getTeam()).as("check team").isEqualTo(actual.getTeam()));
    }
}
