/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.AclObjectIdentityRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclObjectIdentity extends TableImpl<AclObjectIdentityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.acl_object_identity</code>
     */
    public static final AclObjectIdentity ACL_OBJECT_IDENTITY = new AclObjectIdentity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AclObjectIdentityRecord> getRecordType() {
        return AclObjectIdentityRecord.class;
    }

    /**
     * The column <code>public.acl_object_identity.id</code>.
     */
    public final TableField<AclObjectIdentityRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.acl_object_identity.object_id_class</code>.
     */
    public final TableField<AclObjectIdentityRecord, Long> OBJECT_ID_CLASS = createField(DSL.name("object_id_class"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.acl_object_identity.object_id_identity</code>.
     */
    public final TableField<AclObjectIdentityRecord, Long> OBJECT_ID_IDENTITY = createField(DSL.name("object_id_identity"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.acl_object_identity.parent_object</code>.
     */
    public final TableField<AclObjectIdentityRecord, Long> PARENT_OBJECT = createField(DSL.name("parent_object"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.acl_object_identity.owner_sid</code>.
     */
    public final TableField<AclObjectIdentityRecord, Long> OWNER_SID = createField(DSL.name("owner_sid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.acl_object_identity.entries_inheriting</code>.
     */
    public final TableField<AclObjectIdentityRecord, Boolean> ENTRIES_INHERITING = createField(DSL.name("entries_inheriting"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private AclObjectIdentity(Name alias, Table<AclObjectIdentityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AclObjectIdentity(Name alias, Table<AclObjectIdentityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.acl_object_identity</code> table reference
     */
    public AclObjectIdentity(String alias) {
        this(DSL.name(alias), ACL_OBJECT_IDENTITY);
    }

    /**
     * Create an aliased <code>public.acl_object_identity</code> table reference
     */
    public AclObjectIdentity(Name alias) {
        this(alias, ACL_OBJECT_IDENTITY);
    }

    /**
     * Create a <code>public.acl_object_identity</code> table reference
     */
    public AclObjectIdentity() {
        this(DSL.name("acl_object_identity"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AclObjectIdentityRecord, Long> getIdentity() {
        return (Identity<AclObjectIdentityRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AclObjectIdentityRecord> getPrimaryKey() {
        return Keys.PK_ACL_OBJECT_IDENTITY;
    }

    @Override
    public List<UniqueKey<AclObjectIdentityRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_ACL_OBJECT_IDENTITY_CLASS_IDENTITY);
    }

    @Override
    public List<ForeignKey<AclObjectIdentityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ACL_OBJECT_IDENTITY__FK_ACL_OBJECT_IDENTITY_CLASS, Keys.ACL_OBJECT_IDENTITY__FK_ACL_OBJECT_IDENTITY_OWNER, Keys.ACL_OBJECT_IDENTITY__FK_ACL_OBJECT_IDENTITY_PARENT);
    }

    @Override
    public AclObjectIdentity as(String alias) {
        return new AclObjectIdentity(DSL.name(alias), this);
    }

    @Override
    public AclObjectIdentity as(Name alias) {
        return new AclObjectIdentity(alias, this);
    }

    @Override
    public AclObjectIdentity as(Table<?> alias) {
        return new AclObjectIdentity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AclObjectIdentity rename(String name) {
        return new AclObjectIdentity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AclObjectIdentity rename(Name name) {
        return new AclObjectIdentity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AclObjectIdentity rename(Table<?> name) {
        return new AclObjectIdentity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclObjectIdentity where(Condition condition) {
        return new AclObjectIdentity(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclObjectIdentity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclObjectIdentity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclObjectIdentity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AclObjectIdentity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AclObjectIdentity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AclObjectIdentity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AclObjectIdentity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclObjectIdentity whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclObjectIdentity whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
