/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.AclSidRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclSid extends TableImpl<AclSidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.acl_sid</code>
     */
    public static final AclSid ACL_SID = new AclSid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AclSidRecord> getRecordType() {
        return AclSidRecord.class;
    }

    /**
     * The column <code>public.acl_sid.id</code>.
     */
    public final TableField<AclSidRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.acl_sid.principal</code>.
     */
    public final TableField<AclSidRecord, Boolean> PRINCIPAL = createField(DSL.name("principal"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.acl_sid.sid</code>.
     */
    public final TableField<AclSidRecord, String> SID = createField(DSL.name("sid"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private AclSid(Name alias, Table<AclSidRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AclSid(Name alias, Table<AclSidRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.acl_sid</code> table reference
     */
    public AclSid(String alias) {
        this(DSL.name(alias), ACL_SID);
    }

    /**
     * Create an aliased <code>public.acl_sid</code> table reference
     */
    public AclSid(Name alias) {
        this(alias, ACL_SID);
    }

    /**
     * Create a <code>public.acl_sid</code> table reference
     */
    public AclSid() {
        this(DSL.name("acl_sid"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AclSidRecord, Long> getIdentity() {
        return (Identity<AclSidRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AclSidRecord> getPrimaryKey() {
        return Keys.PK_ACL_SID;
    }

    @Override
    public List<UniqueKey<AclSidRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_ACL_SID_SID_PRINCIPAL);
    }

    @Override
    public AclSid as(String alias) {
        return new AclSid(DSL.name(alias), this);
    }

    @Override
    public AclSid as(Name alias) {
        return new AclSid(alias, this);
    }

    @Override
    public AclSid as(Table<?> alias) {
        return new AclSid(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AclSid rename(String name) {
        return new AclSid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AclSid rename(Name name) {
        return new AclSid(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AclSid rename(Table<?> name) {
        return new AclSid(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclSid where(Condition condition) {
        return new AclSid(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclSid where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclSid where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclSid where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AclSid where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AclSid where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AclSid where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AclSid where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclSid whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AclSid whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
