/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.AppAuthorityRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppAuthority extends TableImpl<AppAuthorityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_authority</code>
     */
    public static final AppAuthority APP_AUTHORITY = new AppAuthority();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppAuthorityRecord> getRecordType() {
        return AppAuthorityRecord.class;
    }

    /**
     * The column <code>public.app_authority.name</code>.
     */
    public final TableField<AppAuthorityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private AppAuthority(Name alias, Table<AppAuthorityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppAuthority(Name alias, Table<AppAuthorityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_authority</code> table reference
     */
    public AppAuthority(String alias) {
        this(DSL.name(alias), APP_AUTHORITY);
    }

    /**
     * Create an aliased <code>public.app_authority</code> table reference
     */
    public AppAuthority(Name alias) {
        this(alias, APP_AUTHORITY);
    }

    /**
     * Create a <code>public.app_authority</code> table reference
     */
    public AppAuthority() {
        this(DSL.name("app_authority"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AppAuthorityRecord> getPrimaryKey() {
        return Keys.APP_AUTHORITY_PKEY;
    }

    @Override
    public AppAuthority as(String alias) {
        return new AppAuthority(DSL.name(alias), this);
    }

    @Override
    public AppAuthority as(Name alias) {
        return new AppAuthority(alias, this);
    }

    @Override
    public AppAuthority as(Table<?> alias) {
        return new AppAuthority(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppAuthority rename(String name) {
        return new AppAuthority(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppAuthority rename(Name name) {
        return new AppAuthority(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppAuthority rename(Table<?> name) {
        return new AppAuthority(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppAuthority where(Condition condition) {
        return new AppAuthority(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppAuthority where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppAuthority where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppAuthority where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppAuthority where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppAuthority where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppAuthority where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppAuthority where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppAuthority whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppAuthority whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
