/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Indexes;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.AppEntityAuditEventRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppEntityAuditEvent extends TableImpl<AppEntityAuditEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_entity_audit_event</code>
     */
    public static final AppEntityAuditEvent APP_ENTITY_AUDIT_EVENT = new AppEntityAuditEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppEntityAuditEventRecord> getRecordType() {
        return AppEntityAuditEventRecord.class;
    }

    /**
     * The column <code>public.app_entity_audit_event.id</code>.
     */
    public final TableField<AppEntityAuditEventRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.app_entity_audit_event.entity_id</code>.
     */
    public final TableField<AppEntityAuditEventRecord, String> ENTITY_ID = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.app_entity_audit_event.entity_type</code>.
     */
    public final TableField<AppEntityAuditEventRecord, String> ENTITY_TYPE = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(2500).nullable(false), this, "");

    /**
     * The column <code>public.app_entity_audit_event.action</code>.
     */
    public final TableField<AppEntityAuditEventRecord, String> ACTION = createField(DSL.name("action"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.app_entity_audit_event.entity_value</code>.
     */
    public final TableField<AppEntityAuditEventRecord, String> ENTITY_VALUE = createField(DSL.name("entity_value"), SQLDataType.VARCHAR(50000), this, "");

    /**
     * The column <code>public.app_entity_audit_event.commit_version</code>.
     */
    public final TableField<AppEntityAuditEventRecord, Integer> COMMIT_VERSION = createField(DSL.name("commit_version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.app_entity_audit_event.modified_by</code>.
     */
    public final TableField<AppEntityAuditEventRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.app_entity_audit_event.modified_date</code>.
     */
    public final TableField<AppEntityAuditEventRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private AppEntityAuditEvent(Name alias, Table<AppEntityAuditEventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppEntityAuditEvent(Name alias, Table<AppEntityAuditEventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_entity_audit_event</code> table
     * reference
     */
    public AppEntityAuditEvent(String alias) {
        this(DSL.name(alias), APP_ENTITY_AUDIT_EVENT);
    }

    /**
     * Create an aliased <code>public.app_entity_audit_event</code> table
     * reference
     */
    public AppEntityAuditEvent(Name alias) {
        this(alias, APP_ENTITY_AUDIT_EVENT);
    }

    /**
     * Create a <code>public.app_entity_audit_event</code> table reference
     */
    public AppEntityAuditEvent() {
        this(DSL.name("app_entity_audit_event"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ENTITY_AUDIT_EVENT_ENTITY_TYPE);
    }

    @Override
    public UniqueKey<AppEntityAuditEventRecord> getPrimaryKey() {
        return Keys.PK_APP_ENTITY_AUDIT_EVENT;
    }

    @Override
    public AppEntityAuditEvent as(String alias) {
        return new AppEntityAuditEvent(DSL.name(alias), this);
    }

    @Override
    public AppEntityAuditEvent as(Name alias) {
        return new AppEntityAuditEvent(alias, this);
    }

    @Override
    public AppEntityAuditEvent as(Table<?> alias) {
        return new AppEntityAuditEvent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppEntityAuditEvent rename(String name) {
        return new AppEntityAuditEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppEntityAuditEvent rename(Name name) {
        return new AppEntityAuditEvent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppEntityAuditEvent rename(Table<?> name) {
        return new AppEntityAuditEvent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppEntityAuditEvent where(Condition condition) {
        return new AppEntityAuditEvent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppEntityAuditEvent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppEntityAuditEvent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppEntityAuditEvent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppEntityAuditEvent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppEntityAuditEvent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppEntityAuditEvent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppEntityAuditEvent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppEntityAuditEvent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppEntityAuditEvent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
