/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.AppUserRoleMembersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRoleMembers extends TableImpl<AppUserRoleMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_user_role_members</code>
     */
    public static final AppUserRoleMembers APP_USER_ROLE_MEMBERS = new AppUserRoleMembers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppUserRoleMembersRecord> getRecordType() {
        return AppUserRoleMembersRecord.class;
    }

    /**
     * The column <code>public.app_user_role_members.role_id</code>.
     */
    public final TableField<AppUserRoleMembersRecord, String> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.app_user_role_members.user_id</code>.
     */
    public final TableField<AppUserRoleMembersRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    private AppUserRoleMembers(Name alias, Table<AppUserRoleMembersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppUserRoleMembers(Name alias, Table<AppUserRoleMembersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_user_role_members</code> table
     * reference
     */
    public AppUserRoleMembers(String alias) {
        this(DSL.name(alias), APP_USER_ROLE_MEMBERS);
    }

    /**
     * Create an aliased <code>public.app_user_role_members</code> table
     * reference
     */
    public AppUserRoleMembers(Name alias) {
        this(alias, APP_USER_ROLE_MEMBERS);
    }

    /**
     * Create a <code>public.app_user_role_members</code> table reference
     */
    public AppUserRoleMembers() {
        this(DSL.name("app_user_role_members"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AppUserRoleMembersRecord> getPrimaryKey() {
        return Keys.PK_APP_USER_ROLE_MEMBERS;
    }

    @Override
    public List<ForeignKey<AppUserRoleMembersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.APP_USER_ROLE_MEMBERS__FK_APPUSEROLMEM_ON_ROLE, Keys.APP_USER_ROLE_MEMBERS__FK_APPUSEROLMEM_ON_USER);
    }

    @Override
    public AppUserRoleMembers as(String alias) {
        return new AppUserRoleMembers(DSL.name(alias), this);
    }

    @Override
    public AppUserRoleMembers as(Name alias) {
        return new AppUserRoleMembers(alias, this);
    }

    @Override
    public AppUserRoleMembers as(Table<?> alias) {
        return new AppUserRoleMembers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserRoleMembers rename(String name) {
        return new AppUserRoleMembers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserRoleMembers rename(Name name) {
        return new AppUserRoleMembers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserRoleMembers rename(Table<?> name) {
        return new AppUserRoleMembers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserRoleMembers where(Condition condition) {
        return new AppUserRoleMembers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserRoleMembers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserRoleMembers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserRoleMembers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserRoleMembers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserRoleMembers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserRoleMembers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserRoleMembers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserRoleMembers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserRoleMembers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
