/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.AppUserAuthorityRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserAuthority extends TableImpl<AppUserAuthorityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_user_authority</code>
     */
    public static final AppUserAuthority APP_USER_AUTHORITY = new AppUserAuthority();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppUserAuthorityRecord> getRecordType() {
        return AppUserAuthorityRecord.class;
    }

    /**
     * The column <code>public.app_user_authority.user_id</code>.
     */
    public final TableField<AppUserAuthorityRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.app_user_authority.authority_name</code>.
     */
    public final TableField<AppUserAuthorityRecord, String> AUTHORITY_NAME = createField(DSL.name("authority_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private AppUserAuthority(Name alias, Table<AppUserAuthorityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppUserAuthority(Name alias, Table<AppUserAuthorityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_user_authority</code> table reference
     */
    public AppUserAuthority(String alias) {
        this(DSL.name(alias), APP_USER_AUTHORITY);
    }

    /**
     * Create an aliased <code>public.app_user_authority</code> table reference
     */
    public AppUserAuthority(Name alias) {
        this(alias, APP_USER_AUTHORITY);
    }

    /**
     * Create a <code>public.app_user_authority</code> table reference
     */
    public AppUserAuthority() {
        this(DSL.name("app_user_authority"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AppUserAuthorityRecord> getPrimaryKey() {
        return Keys.PK_APP_USER_AUTHORITY;
    }

    @Override
    public List<ForeignKey<AppUserAuthorityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.APP_USER_AUTHORITY__FK_AUTHORITY_NAME, Keys.APP_USER_AUTHORITY__FK_USER_ID);
    }

    @Override
    public AppUserAuthority as(String alias) {
        return new AppUserAuthority(DSL.name(alias), this);
    }

    @Override
    public AppUserAuthority as(Name alias) {
        return new AppUserAuthority(alias, this);
    }

    @Override
    public AppUserAuthority as(Table<?> alias) {
        return new AppUserAuthority(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserAuthority rename(String name) {
        return new AppUserAuthority(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserAuthority rename(Name name) {
        return new AppUserAuthority(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserAuthority rename(Table<?> name) {
        return new AppUserAuthority(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserAuthority where(Condition condition) {
        return new AppUserAuthority(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserAuthority where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserAuthority where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserAuthority where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserAuthority where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserAuthority where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserAuthority where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserAuthority where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserAuthority whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserAuthority whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
