/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.DataElementGroupMembersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataElementGroupMembers extends TableImpl<DataElementGroupMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.data_element_group_members</code>
     */
    public static final DataElementGroupMembers DATA_ELEMENT_GROUP_MEMBERS = new DataElementGroupMembers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataElementGroupMembersRecord> getRecordType() {
        return DataElementGroupMembersRecord.class;
    }

    /**
     * The column <code>public.data_element_group_members.group_id</code>.
     */
    public final TableField<DataElementGroupMembersRecord, String> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column
     * <code>public.data_element_group_members.data_element_id</code>.
     */
    public final TableField<DataElementGroupMembersRecord, String> DATA_ELEMENT_ID = createField(DSL.name("data_element_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    private DataElementGroupMembers(Name alias, Table<DataElementGroupMembersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DataElementGroupMembers(Name alias, Table<DataElementGroupMembersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.data_element_group_members</code> table
     * reference
     */
    public DataElementGroupMembers(String alias) {
        this(DSL.name(alias), DATA_ELEMENT_GROUP_MEMBERS);
    }

    /**
     * Create an aliased <code>public.data_element_group_members</code> table
     * reference
     */
    public DataElementGroupMembers(Name alias) {
        this(alias, DATA_ELEMENT_GROUP_MEMBERS);
    }

    /**
     * Create a <code>public.data_element_group_members</code> table reference
     */
    public DataElementGroupMembers() {
        this(DSL.name("data_element_group_members"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<DataElementGroupMembersRecord> getPrimaryKey() {
        return Keys.PK_DATA_ELEMENT_GROUP_MEMBERS;
    }

    @Override
    public List<ForeignKey<DataElementGroupMembersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DATA_ELEMENT_GROUP_MEMBERS__FK_DATELEGROMEM_ON_DATA_ELEMENT_GROUP, Keys.DATA_ELEMENT_GROUP_MEMBERS__FK_DATELEGROMEM_ON_DATA_TEMPLATE_ELEMENT);
    }

    @Override
    public DataElementGroupMembers as(String alias) {
        return new DataElementGroupMembers(DSL.name(alias), this);
    }

    @Override
    public DataElementGroupMembers as(Name alias) {
        return new DataElementGroupMembers(alias, this);
    }

    @Override
    public DataElementGroupMembers as(Table<?> alias) {
        return new DataElementGroupMembers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DataElementGroupMembers rename(String name) {
        return new DataElementGroupMembers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataElementGroupMembers rename(Name name) {
        return new DataElementGroupMembers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataElementGroupMembers rename(Table<?> name) {
        return new DataElementGroupMembers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupMembers where(Condition condition) {
        return new DataElementGroupMembers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupMembers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupMembers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupMembers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElementGroupMembers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElementGroupMembers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElementGroupMembers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElementGroupMembers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupMembers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupMembers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
