/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Indexes;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.DataSubmissionRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataSubmission extends TableImpl<DataSubmissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.data_submission</code>
     */
    public static final DataSubmission DATA_SUBMISSION = new DataSubmission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataSubmissionRecord> getRecordType() {
        return DataSubmissionRecord.class;
    }

    /**
     * The column <code>public.data_submission.id</code>.
     */
    public final TableField<DataSubmissionRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.data_submission.serial_number</code>.
     */
    public final TableField<DataSubmissionRecord, Long> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.data_submission.uid</code>.
     */
    public final TableField<DataSubmissionRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.data_submission.template_uid</code>.
     */
    public final TableField<DataSubmissionRecord, String> TEMPLATE_UID = createField(DSL.name("template_uid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.data_submission.template_version_uid</code>.
     */
    public final TableField<DataSubmissionRecord, String> TEMPLATE_VERSION_UID = createField(DSL.name("template_version_uid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.data_submission.template_version_no</code>.
     */
    public final TableField<DataSubmissionRecord, Integer> TEMPLATE_VERSION_NO = createField(DSL.name("template_version_no"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.data_submission.submission_version</code>.
     */
    public final TableField<DataSubmissionRecord, Integer> SUBMISSION_VERSION = createField(DSL.name("submission_version"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.data_submission.assignment_uid</code>.
     */
    public final TableField<DataSubmissionRecord, String> ASSIGNMENT_UID = createField(DSL.name("assignment_uid"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.data_submission.activity_uid</code>.
     */
    public final TableField<DataSubmissionRecord, String> ACTIVITY_UID = createField(DSL.name("activity_uid"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.data_submission.team_uid</code>.
     */
    public final TableField<DataSubmissionRecord, String> TEAM_UID = createField(DSL.name("team_uid"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.data_submission.team_code</code>.
     */
    public final TableField<DataSubmissionRecord, String> TEAM_CODE = createField(DSL.name("team_code"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.data_submission.org_unit_uid</code>.
     */
    public final TableField<DataSubmissionRecord, String> ORG_UNIT_UID = createField(DSL.name("org_unit_uid"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.data_submission.org_unit_code</code>.
     */
    public final TableField<DataSubmissionRecord, String> ORG_UNIT_CODE = createField(DSL.name("org_unit_code"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.data_submission.org_unit_name</code>.
     */
    public final TableField<DataSubmissionRecord, String> ORG_UNIT_NAME = createField(DSL.name("org_unit_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.data_submission.status</code>.
     */
    public final TableField<DataSubmissionRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.data_submission.start_entry_time</code>.
     */
    public final TableField<DataSubmissionRecord, LocalDateTime> START_ENTRY_TIME = createField(DSL.name("start_entry_time"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_submission.finished_entry_time</code>.
     */
    public final TableField<DataSubmissionRecord, LocalDateTime> FINISHED_ENTRY_TIME = createField(DSL.name("finished_entry_time"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_submission.form_data</code>.
     */
    public final TableField<DataSubmissionRecord, JSONB> FORM_DATA = createField(DSL.name("form_data"), SQLDataType.JSONB.defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.data_submission.lock_version</code>.
     */
    public final TableField<DataSubmissionRecord, Long> LOCK_VERSION = createField(DSL.name("lock_version"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.data_submission.created_by</code>.
     */
    public final TableField<DataSubmissionRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.data_submission.created_date</code>.
     */
    public final TableField<DataSubmissionRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.data_submission.last_modified_by</code>.
     */
    public final TableField<DataSubmissionRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.data_submission.last_modified_date</code>.
     */
    public final TableField<DataSubmissionRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_submission.translations</code>.
     */
    public final TableField<DataSubmissionRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.data_submission.deleted</code>.
     */
    public final TableField<DataSubmissionRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.data_submission.deleted_at</code>.
     */
    public final TableField<DataSubmissionRecord, LocalDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_submission.properties_map</code>.
     */
    public final TableField<DataSubmissionRecord, JSONB> PROPERTIES_MAP = createField(DSL.name("properties_map"), SQLDataType.JSONB, this, "");

    private DataSubmission(Name alias, Table<DataSubmissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DataSubmission(Name alias, Table<DataSubmissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.data_submission</code> table reference
     */
    public DataSubmission(String alias) {
        this(DSL.name(alias), DATA_SUBMISSION);
    }

    /**
     * Create an aliased <code>public.data_submission</code> table reference
     */
    public DataSubmission(Name alias) {
        this(alias, DATA_SUBMISSION);
    }

    /**
     * Create a <code>public.data_submission</code> table reference
     */
    public DataSubmission() {
        this(DSL.name("data_submission"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_DS_ACTIVE_FORM_ASSIGNMENT, Indexes.IDX_DS_FORM_ASSIGNMENT, Indexes.IDX_DS_FORM_DATA_GIN, Indexes.IDX_DS_ORGUNIT, Indexes.IDX_DS_SERIAL_NUMBER);
    }

    @Override
    public Identity<DataSubmissionRecord, Long> getIdentity() {
        return (Identity<DataSubmissionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DataSubmissionRecord> getPrimaryKey() {
        return Keys.DATA_SUBMISSION_PKEY;
    }

    @Override
    public List<UniqueKey<DataSubmissionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_DATA_SUBMISSION_SERIAL, Keys.UK_DATA_SUBMISSION_UID);
    }

    @Override
    public DataSubmission as(String alias) {
        return new DataSubmission(DSL.name(alias), this);
    }

    @Override
    public DataSubmission as(Name alias) {
        return new DataSubmission(alias, this);
    }

    @Override
    public DataSubmission as(Table<?> alias) {
        return new DataSubmission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DataSubmission rename(String name) {
        return new DataSubmission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataSubmission rename(Name name) {
        return new DataSubmission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataSubmission rename(Table<?> name) {
        return new DataSubmission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataSubmission where(Condition condition) {
        return new DataSubmission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataSubmission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataSubmission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataSubmission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataSubmission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataSubmission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataSubmission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataSubmission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataSubmission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataSubmission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
