/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.DataElementRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataElement extends TableImpl<DataElementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.data_element</code>
     */
    public static final DataElement DATA_ELEMENT = new DataElement();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataElementRecord> getRecordType() {
        return DataElementRecord.class;
    }

    /**
     * The column <code>public.data_element.id</code>.
     */
    public final TableField<DataElementRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.data_element.uid</code>.
     */
    public final TableField<DataElementRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.data_element.code</code>.
     */
    public final TableField<DataElementRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.data_element.name</code>.
     */
    public final TableField<DataElementRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.data_element.short_name</code>.
     */
    public final TableField<DataElementRecord, String> SHORT_NAME = createField(DSL.name("short_name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.data_element.description</code>.
     */
    public final TableField<DataElementRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(2000), this, "");

    /**
     * The column <code>public.data_element.type</code>.
     */
    public final TableField<DataElementRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.data_element.option_set_id</code>.
     */
    public final TableField<DataElementRecord, String> OPTION_SET_ID = createField(DSL.name("option_set_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.data_element.reference_type</code>.
     */
    public final TableField<DataElementRecord, String> REFERENCE_TYPE = createField(DSL.name("reference_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.data_element.translations</code>.
     */
    public final TableField<DataElementRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.data_element.created_by</code>.
     */
    public final TableField<DataElementRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.data_element.created_date</code>.
     */
    public final TableField<DataElementRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_element.last_modified_by</code>.
     */
    public final TableField<DataElementRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.data_element.last_modified_date</code>.
     */
    public final TableField<DataElementRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_element.is_measure</code>.
     */
    public final TableField<DataElementRecord, Boolean> IS_MEASURE = createField(DSL.name("is_measure"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.data_element.aggregation_type</code>.
     */
    public final TableField<DataElementRecord, String> AGGREGATION_TYPE = createField(DSL.name("aggregation_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.data_element.is_dimension</code>.
     */
    public final TableField<DataElementRecord, Boolean> IS_DIMENSION = createField(DSL.name("is_dimension"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.data_element.properties_map</code>.
     */
    public final TableField<DataElementRecord, JSONB> PROPERTIES_MAP = createField(DSL.name("properties_map"), SQLDataType.JSONB, this, "");

    private DataElement(Name alias, Table<DataElementRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DataElement(Name alias, Table<DataElementRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.data_element</code> table reference
     */
    public DataElement(String alias) {
        this(DSL.name(alias), DATA_ELEMENT);
    }

    /**
     * Create an aliased <code>public.data_element</code> table reference
     */
    public DataElement(Name alias) {
        this(alias, DATA_ELEMENT);
    }

    /**
     * Create a <code>public.data_element</code> table reference
     */
    public DataElement() {
        this(DSL.name("data_element"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<DataElementRecord> getPrimaryKey() {
        return Keys.PK_DATA_ELEMENT;
    }

    @Override
    public List<UniqueKey<DataElementRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_DATA_ELEMENT_CODE, Keys.UC_DATA_ELEMENT_NAME, Keys.UC_DATA_ELEMENT_UID);
    }

    @Override
    public List<ForeignKey<DataElementRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DATA_ELEMENT__FK_DATA_ELEMENT_ON_OPTIONSET);
    }

    @Override
    public DataElement as(String alias) {
        return new DataElement(DSL.name(alias), this);
    }

    @Override
    public DataElement as(Name alias) {
        return new DataElement(alias, this);
    }

    @Override
    public DataElement as(Table<?> alias) {
        return new DataElement(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DataElement rename(String name) {
        return new DataElement(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataElement rename(Name name) {
        return new DataElement(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataElement rename(Table<?> name) {
        return new DataElement(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElement where(Condition condition) {
        return new DataElement(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElement where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElement where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElement where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElement where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElement where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElement where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElement where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElement whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElement whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
