/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.DataElementGroupsetRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataElementGroupset extends TableImpl<DataElementGroupsetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.data_element_groupset</code>
     */
    public static final DataElementGroupset DATA_ELEMENT_GROUPSET = new DataElementGroupset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataElementGroupsetRecord> getRecordType() {
        return DataElementGroupsetRecord.class;
    }

    /**
     * The column <code>public.data_element_groupset.id</code>.
     */
    public final TableField<DataElementGroupsetRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.data_element_groupset.uid</code>.
     */
    public final TableField<DataElementGroupsetRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.data_element_groupset.code</code>.
     */
    public final TableField<DataElementGroupsetRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.data_element_groupset.name</code>.
     */
    public final TableField<DataElementGroupsetRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.data_element_groupset.translations</code>.
     */
    public final TableField<DataElementGroupsetRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.data_element_groupset.created_by</code>.
     */
    public final TableField<DataElementGroupsetRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.data_element_groupset.created_date</code>.
     */
    public final TableField<DataElementGroupsetRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_element_groupset.last_modified_by</code>.
     */
    public final TableField<DataElementGroupsetRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.data_element_groupset.last_modified_date</code>.
     */
    public final TableField<DataElementGroupsetRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_element_groupset.properties_map</code>.
     */
    public final TableField<DataElementGroupsetRecord, JSONB> PROPERTIES_MAP = createField(DSL.name("properties_map"), SQLDataType.JSONB, this, "");

    private DataElementGroupset(Name alias, Table<DataElementGroupsetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DataElementGroupset(Name alias, Table<DataElementGroupsetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.data_element_groupset</code> table
     * reference
     */
    public DataElementGroupset(String alias) {
        this(DSL.name(alias), DATA_ELEMENT_GROUPSET);
    }

    /**
     * Create an aliased <code>public.data_element_groupset</code> table
     * reference
     */
    public DataElementGroupset(Name alias) {
        this(alias, DATA_ELEMENT_GROUPSET);
    }

    /**
     * Create a <code>public.data_element_groupset</code> table reference
     */
    public DataElementGroupset() {
        this(DSL.name("data_element_groupset"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<DataElementGroupsetRecord> getPrimaryKey() {
        return Keys.PK_DATA_ELEMENT_GROUPSET;
    }

    @Override
    public List<UniqueKey<DataElementGroupsetRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_DATA_ELEMENT_GROUPSET_CODE, Keys.UC_DATA_ELEMENT_GROUPSET_NAME, Keys.UC_DATA_ELEMENT_GROUPSET_UID);
    }

    @Override
    public DataElementGroupset as(String alias) {
        return new DataElementGroupset(DSL.name(alias), this);
    }

    @Override
    public DataElementGroupset as(Name alias) {
        return new DataElementGroupset(alias, this);
    }

    @Override
    public DataElementGroupset as(Table<?> alias) {
        return new DataElementGroupset(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DataElementGroupset rename(String name) {
        return new DataElementGroupset(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataElementGroupset rename(Name name) {
        return new DataElementGroupset(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataElementGroupset rename(Table<?> name) {
        return new DataElementGroupset(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupset where(Condition condition) {
        return new DataElementGroupset(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupset where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupset where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupset where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElementGroupset where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElementGroupset where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElementGroupset where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataElementGroupset where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupset whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataElementGroupset whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
