/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Indexes;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.ElementDataValueRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElementDataValue extends TableImpl<ElementDataValueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.element_data_value</code>
     */
    public static final ElementDataValue ELEMENT_DATA_VALUE = new ElementDataValue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ElementDataValueRecord> getRecordType() {
        return ElementDataValueRecord.class;
    }

    /**
     * The column <code>public.element_data_value.id</code>.
     */
    public final TableField<ElementDataValueRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.element_data_value.repeat_instance_id</code>.
     */
    public final TableField<ElementDataValueRecord, String> REPEAT_INSTANCE_ID = createField(DSL.name("repeat_instance_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.element_data_value.submission_uid</code>.
     */
    public final TableField<ElementDataValueRecord, String> SUBMISSION_UID = createField(DSL.name("submission_uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.element_data_value.semantic_path</code>.
     */
    public final TableField<ElementDataValueRecord, String> SEMANTIC_PATH = createField(DSL.name("semantic_path"), SQLDataType.VARCHAR(3000).nullable(false), this, "");

    /**
     * The column <code>public.element_data_value.assignment_uid</code>.
     */
    public final TableField<ElementDataValueRecord, String> ASSIGNMENT_UID = createField(DSL.name("assignment_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.element_data_value.team_uid</code>.
     */
    public final TableField<ElementDataValueRecord, String> TEAM_UID = createField(DSL.name("team_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.element_data_value.org_unit_uid</code>.
     */
    public final TableField<ElementDataValueRecord, String> ORG_UNIT_UID = createField(DSL.name("org_unit_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.element_data_value.activity_uid</code>.
     */
    public final TableField<ElementDataValueRecord, String> ACTIVITY_UID = createField(DSL.name("activity_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.element_data_value.element_uid</code>.
     */
    public final TableField<ElementDataValueRecord, String> ELEMENT_UID = createField(DSL.name("element_uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column
     * <code>public.element_data_value.element_template_config_uid</code>.
     */
    public final TableField<ElementDataValueRecord, String> ELEMENT_TEMPLATE_CONFIG_UID = createField(DSL.name("element_template_config_uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.element_data_value.option_uid</code>.
     */
    public final TableField<ElementDataValueRecord, String> OPTION_UID = createField(DSL.name("option_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.element_data_value.value_text</code>.
     */
    public final TableField<ElementDataValueRecord, String> VALUE_TEXT = createField(DSL.name("value_text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.element_data_value.value_num</code>.
     */
    public final TableField<ElementDataValueRecord, BigDecimal> VALUE_NUM = createField(DSL.name("value_num"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.element_data_value.value_bool</code>.
     */
    public final TableField<ElementDataValueRecord, Boolean> VALUE_BOOL = createField(DSL.name("value_bool"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.element_data_value.value_ref_uid</code>.
     */
    public final TableField<ElementDataValueRecord, String> VALUE_REF_UID = createField(DSL.name("value_ref_uid"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.element_data_value.value_ts</code>.
     */
    public final TableField<ElementDataValueRecord, LocalDateTime> VALUE_TS = createField(DSL.name("value_ts"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.element_data_value.deleted_at</code>.
     */
    public final TableField<ElementDataValueRecord, LocalDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.element_data_value.created_date</code>.
     */
    public final TableField<ElementDataValueRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.element_data_value.last_modified_date</code>.
     */
    public final TableField<ElementDataValueRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.element_data_value.repeat_instance_key</code>.
     */
    public final TableField<ElementDataValueRecord, String> REPEAT_INSTANCE_KEY = createField(DSL.name("repeat_instance_key"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.element_data_value.selection_key</code>.
     */
    public final TableField<ElementDataValueRecord, String> SELECTION_KEY = createField(DSL.name("selection_key"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.element_data_value.row_type</code>.
     */
    public final TableField<ElementDataValueRecord, String> ROW_TYPE = createField(DSL.name("row_type"), SQLDataType.CHAR(1).nullable(false).defaultValue(DSL.field(DSL.raw("'S'::bpchar"), SQLDataType.CHAR)), this, "");

    /**
     * The column <code>public.element_data_value.value_as_text</code>.
     */
    public final TableField<ElementDataValueRecord, String> VALUE_AS_TEXT = createField(DSL.name("value_as_text"), SQLDataType.CLOB, this, "");

    private ElementDataValue(Name alias, Table<ElementDataValueRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ElementDataValue(Name alias, Table<ElementDataValueRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.element_data_value</code> table reference
     */
    public ElementDataValue(String alias) {
        this(DSL.name(alias), ELEMENT_DATA_VALUE);
    }

    /**
     * Create an aliased <code>public.element_data_value</code> table reference
     */
    public ElementDataValue(Name alias) {
        this(alias, ELEMENT_DATA_VALUE);
    }

    /**
     * Create a <code>public.element_data_value</code> table reference
     */
    public ElementDataValue() {
        this(DSL.name("element_data_value"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_EDV_ELEMENT_ACTIVE, Indexes.IDX_EDV_TEAM_ACTIVE, Indexes.IDX_ELEMENT_DATA_VALUE_SUBMISSION_REPEAT, Indexes.UX_ELEMENT_VALUE_UNIQUE);
    }

    @Override
    public Identity<ElementDataValueRecord, Long> getIdentity() {
        return (Identity<ElementDataValueRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ElementDataValueRecord> getPrimaryKey() {
        return Keys.ELEMENT_DATA_VALUE_PKEY;
    }

    @Override
    public ElementDataValue as(String alias) {
        return new ElementDataValue(DSL.name(alias), this);
    }

    @Override
    public ElementDataValue as(Name alias) {
        return new ElementDataValue(alias, this);
    }

    @Override
    public ElementDataValue as(Table<?> alias) {
        return new ElementDataValue(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ElementDataValue rename(String name) {
        return new ElementDataValue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ElementDataValue rename(Name name) {
        return new ElementDataValue(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ElementDataValue rename(Table<?> name) {
        return new ElementDataValue(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementDataValue where(Condition condition) {
        return new ElementDataValue(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementDataValue where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementDataValue where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementDataValue where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ElementDataValue where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ElementDataValue where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ElementDataValue where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ElementDataValue where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementDataValue whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementDataValue whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
