/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Indexes;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.ElementTemplateConfigRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElementTemplateConfig extends TableImpl<ElementTemplateConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.template_element</code>
     */
    public static final ElementTemplateConfig ELEMENT_TEMPLATE_CONFIG = new ElementTemplateConfig();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ElementTemplateConfigRecord> getRecordType() {
        return ElementTemplateConfigRecord.class;
    }

    /**
     * The column <code>public.template_element.id</code>.
     */
    public final TableField<ElementTemplateConfigRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.template_element.uid</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.template_element.element_kind</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> ELEMENT_KIND = createField(DSL.name("element_kind"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.template_element.template_uid</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> TEMPLATE_UID = createField(DSL.name("template_uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column
     * <code>public.template_element.template_version_uid</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> TEMPLATE_VERSION_UID = createField(DSL.name("template_version_uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column
     * <code>public.template_element.template_version_no</code>.
     */
    public final TableField<ElementTemplateConfigRecord, Integer> TEMPLATE_VERSION_NO = createField(DSL.name("template_version_no"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.template_element.data_element_uid</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> DATA_ELEMENT_UID = createField(DSL.name("data_element_uid"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.template_element.name</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.template_element.value_type</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> VALUE_TYPE = createField(DSL.name("value_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.template_element.aggregation_type</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> AGGREGATION_TYPE = createField(DSL.name("aggregation_type"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.template_element.is_reference</code>.
     */
    public final TableField<ElementTemplateConfigRecord, Boolean> IS_REFERENCE = createField(DSL.name("is_reference"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.template_element.category_id</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.template_element.is_category</code>.
     */
    public final TableField<ElementTemplateConfigRecord, Boolean> IS_CATEGORY = createField(DSL.name("is_category"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.template_element.option_set_uid</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> OPTION_SET_UID = createField(DSL.name("option_set_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.template_element.is_multi</code>.
     */
    public final TableField<ElementTemplateConfigRecord, Boolean> IS_MULTI = createField(DSL.name("is_multi"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.template_element.is_measure</code>.
     */
    public final TableField<ElementTemplateConfigRecord, Boolean> IS_MEASURE = createField(DSL.name("is_measure"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.template_element.is_dimension</code>.
     */
    public final TableField<ElementTemplateConfigRecord, Boolean> IS_DIMENSION = createField(DSL.name("is_dimension"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.template_element.sort_order</code>.
     */
    public final TableField<ElementTemplateConfigRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.template_element.semantic_grain</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> SEMANTIC_GRAIN = createField(DSL.name("semantic_grain"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.template_element.id_path</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> ID_PATH = createField(DSL.name("id_path"), SQLDataType.VARCHAR(3000).nullable(false), this, "");

    /**
     * The column <code>public.template_element.path_hash</code>.
     */
    public final TableField<ElementTemplateConfigRecord, Long> PATH_HASH = createField(DSL.name("path_hash"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.template_element.name_path</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> NAME_PATH = createField(DSL.name("name_path"), SQLDataType.VARCHAR(3000), this, "");

    /**
     * The column <code>public.template_element.semantic_path</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> SEMANTIC_PATH = createField(DSL.name("semantic_path"), SQLDataType.VARCHAR(3000), this, "");

    /**
     * The column
     * <code>public.template_element.has_repeat_ancestor</code>.
     */
    public final TableField<ElementTemplateConfigRecord, Boolean> HAS_REPEAT_ANCESTOR = createField(DSL.name("has_repeat_ancestor"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column
     * <code>public.template_element.ancestor_repeat_semantic_path</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> ANCESTOR_REPEAT_SEMANTIC_PATH = createField(DSL.name("ancestor_repeat_semantic_path"), SQLDataType.VARCHAR(3000), this, "");

    /**
     * The column
     * <code>public.template_element.ancestor_repeat_path</code>.
     */
    public final TableField<ElementTemplateConfigRecord, String> ANCESTOR_REPEAT_PATH = createField(DSL.name("ancestor_repeat_path"), SQLDataType.VARCHAR(3000), this, "");

    /**
     * The column <code>public.template_element.display_label</code>.
     */
    public final TableField<ElementTemplateConfigRecord, JSONB> DISPLAY_LABEL = createField(DSL.name("display_label"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.template_element.definition_json</code>.
     */
    public final TableField<ElementTemplateConfigRecord, JSONB> DEFINITION_JSON = createField(DSL.name("definition_json"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.template_element.created_at</code>.
     */
    public final TableField<ElementTemplateConfigRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private ElementTemplateConfig(Name alias, Table<ElementTemplateConfigRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ElementTemplateConfig(Name alias, Table<ElementTemplateConfigRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.template_element</code> table
     * reference
     */
    public ElementTemplateConfig(String alias) {
        this(DSL.name(alias), ELEMENT_TEMPLATE_CONFIG);
    }

    /**
     * Create an aliased <code>public.template_element</code> table
     * reference
     */
    public ElementTemplateConfig(Name alias) {
        this(alias, ELEMENT_TEMPLATE_CONFIG);
    }

    /**
     * Create a <code>public.template_element</code> table reference
     */
    public ElementTemplateConfig() {
        this(DSL.name("template_element"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ELEMENT_TEMPLATE_CONFIG_DATAELEMENT, Indexes.IDX_ELEMENT_TEMPLATE_CONFIG_REPEAT_PATH, Indexes.IDX_ELEMENT_TEMPLATE_CONFIG_TEMPLATE_VERSION, Indexes.IDX_ELEMENT_TEMPLATE_CONFIG_TEMPLATE_VERSION_NO);
    }

    @Override
    public UniqueKey<ElementTemplateConfigRecord> getPrimaryKey() {
        return Keys.PK_ELEMENT_TEMPLATE_CONFIG;
    }

    @Override
    public List<UniqueKey<ElementTemplateConfigRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_ELEMENT_TEMPLATE_CONFIG_UID, Keys.UX_ELEMENT_TEMPLATE_CONFIG_TPL_VER_IDPATH);
    }

    @Override
    public ElementTemplateConfig as(String alias) {
        return new ElementTemplateConfig(DSL.name(alias), this);
    }

    @Override
    public ElementTemplateConfig as(Name alias) {
        return new ElementTemplateConfig(alias, this);
    }

    @Override
    public ElementTemplateConfig as(Table<?> alias) {
        return new ElementTemplateConfig(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ElementTemplateConfig rename(String name) {
        return new ElementTemplateConfig(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ElementTemplateConfig rename(Name name) {
        return new ElementTemplateConfig(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ElementTemplateConfig rename(Table<?> name) {
        return new ElementTemplateConfig(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementTemplateConfig where(Condition condition) {
        return new ElementTemplateConfig(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementTemplateConfig where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementTemplateConfig where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementTemplateConfig where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ElementTemplateConfig where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ElementTemplateConfig where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ElementTemplateConfig where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ElementTemplateConfig where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementTemplateConfig whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ElementTemplateConfig whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
