/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.OptionGroupRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OptionGroup extends TableImpl<OptionGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.option_group</code>
     */
    public static final OptionGroup OPTION_GROUP = new OptionGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OptionGroupRecord> getRecordType() {
        return OptionGroupRecord.class;
    }

    /**
     * The column <code>public.option_group.id</code>.
     */
    public final TableField<OptionGroupRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.option_group.translations</code>.
     */
    public final TableField<OptionGroupRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.option_group.code</code>.
     */
    public final TableField<OptionGroupRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.option_group.name</code>.
     */
    public final TableField<OptionGroupRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.option_group.shortname</code>.
     */
    public final TableField<OptionGroupRecord, String> SHORTNAME = createField(DSL.name("shortname"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.option_group.description</code>.
     */
    public final TableField<OptionGroupRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.option_group.created_by</code>.
     */
    public final TableField<OptionGroupRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.option_group.created_date</code>.
     */
    public final TableField<OptionGroupRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.option_group.last_modified_by</code>.
     */
    public final TableField<OptionGroupRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.option_group.last_modified_date</code>.
     */
    public final TableField<OptionGroupRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.option_group.option_set_id</code>.
     */
    public final TableField<OptionGroupRecord, String> OPTION_SET_ID = createField(DSL.name("option_set_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.option_group.properties_map</code>.
     */
    public final TableField<OptionGroupRecord, JSONB> PROPERTIES_MAP = createField(DSL.name("properties_map"), SQLDataType.JSONB, this, "");

    private OptionGroup(Name alias, Table<OptionGroupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OptionGroup(Name alias, Table<OptionGroupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.option_group</code> table reference
     */
    public OptionGroup(String alias) {
        this(DSL.name(alias), OPTION_GROUP);
    }

    /**
     * Create an aliased <code>public.option_group</code> table reference
     */
    public OptionGroup(Name alias) {
        this(alias, OPTION_GROUP);
    }

    /**
     * Create a <code>public.option_group</code> table reference
     */
    public OptionGroup() {
        this(DSL.name("option_group"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OptionGroupRecord> getPrimaryKey() {
        return Keys.PK_OPTION_GROUP;
    }

    @Override
    public List<UniqueKey<OptionGroupRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_GROUP_OPTION_SET_CODE, Keys.UC_GROUP_OPTION_SET_NAME);
    }

    @Override
    public List<ForeignKey<OptionGroupRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OPTION_GROUP__FK_OPTION_GROUP_ON_OPTION_SET);
    }

    @Override
    public OptionGroup as(String alias) {
        return new OptionGroup(DSL.name(alias), this);
    }

    @Override
    public OptionGroup as(Name alias) {
        return new OptionGroup(alias, this);
    }

    @Override
    public OptionGroup as(Table<?> alias) {
        return new OptionGroup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OptionGroup rename(String name) {
        return new OptionGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OptionGroup rename(Name name) {
        return new OptionGroup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OptionGroup rename(Table<?> name) {
        return new OptionGroup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup where(Condition condition) {
        return new OptionGroup(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
