/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.OptionGroupset_OptionGroupRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OptionGroupset_OptionGroup extends TableImpl<OptionGroupset_OptionGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.option_groupset__option_group</code>
     */
    public static final OptionGroupset_OptionGroup OPTION_GROUPSET__OPTION_GROUP = new OptionGroupset_OptionGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OptionGroupset_OptionGroupRecord> getRecordType() {
        return OptionGroupset_OptionGroupRecord.class;
    }

    /**
     * The column <code>public.option_groupset__option_group.groupset_id</code>.
     */
    public final TableField<OptionGroupset_OptionGroupRecord, String> GROUPSET_ID = createField(DSL.name("groupset_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column
     * <code>public.option_groupset__option_group.option_group_id</code>.
     */
    public final TableField<OptionGroupset_OptionGroupRecord, String> OPTION_GROUP_ID = createField(DSL.name("option_group_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.option_groupset__option_group.sort_order</code>.
     */
    public final TableField<OptionGroupset_OptionGroupRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    private OptionGroupset_OptionGroup(Name alias, Table<OptionGroupset_OptionGroupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OptionGroupset_OptionGroup(Name alias, Table<OptionGroupset_OptionGroupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.option_groupset__option_group</code> table
     * reference
     */
    public OptionGroupset_OptionGroup(String alias) {
        this(DSL.name(alias), OPTION_GROUPSET__OPTION_GROUP);
    }

    /**
     * Create an aliased <code>public.option_groupset__option_group</code> table
     * reference
     */
    public OptionGroupset_OptionGroup(Name alias) {
        this(alias, OPTION_GROUPSET__OPTION_GROUP);
    }

    /**
     * Create a <code>public.option_groupset__option_group</code> table
     * reference
     */
    public OptionGroupset_OptionGroup() {
        this(DSL.name("option_groupset__option_group"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OptionGroupset_OptionGroupRecord> getPrimaryKey() {
        return Keys.PK_OPTION_GROUPSET__OPTION_GROUP;
    }

    @Override
    public List<ForeignKey<OptionGroupset_OptionGroupRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OPTION_GROUPSET__OPTION_GROUP__FK_OPTGROOPTGRO_ON_OPTION_GROUP, Keys.OPTION_GROUPSET__OPTION_GROUP__FK_OPTGROOPTGRO_ON_OPTION_GROUP_SET);
    }

    @Override
    public OptionGroupset_OptionGroup as(String alias) {
        return new OptionGroupset_OptionGroup(DSL.name(alias), this);
    }

    @Override
    public OptionGroupset_OptionGroup as(Name alias) {
        return new OptionGroupset_OptionGroup(alias, this);
    }

    @Override
    public OptionGroupset_OptionGroup as(Table<?> alias) {
        return new OptionGroupset_OptionGroup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OptionGroupset_OptionGroup rename(String name) {
        return new OptionGroupset_OptionGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OptionGroupset_OptionGroup rename(Name name) {
        return new OptionGroupset_OptionGroup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OptionGroupset_OptionGroup rename(Table<?> name) {
        return new OptionGroupset_OptionGroup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroupset_OptionGroup where(Condition condition) {
        return new OptionGroupset_OptionGroup(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroupset_OptionGroup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroupset_OptionGroup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroupset_OptionGroup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroupset_OptionGroup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroupset_OptionGroup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroupset_OptionGroup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroupset_OptionGroup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroupset_OptionGroup whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroupset_OptionGroup whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
