/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.OptionGroup_OptionsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OptionGroup_Options extends TableImpl<OptionGroup_OptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.option_group__options</code>
     */
    public static final OptionGroup_Options OPTION_GROUP__OPTIONS = new OptionGroup_Options();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OptionGroup_OptionsRecord> getRecordType() {
        return OptionGroup_OptionsRecord.class;
    }

    /**
     * The column <code>public.option_group__options.option_group_id</code>.
     */
    public final TableField<OptionGroup_OptionsRecord, String> OPTION_GROUP_ID = createField(DSL.name("option_group_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.option_group__options.option_id</code>.
     */
    public final TableField<OptionGroup_OptionsRecord, String> OPTION_ID = createField(DSL.name("option_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    private OptionGroup_Options(Name alias, Table<OptionGroup_OptionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OptionGroup_Options(Name alias, Table<OptionGroup_OptionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.option_group__options</code> table
     * reference
     */
    public OptionGroup_Options(String alias) {
        this(DSL.name(alias), OPTION_GROUP__OPTIONS);
    }

    /**
     * Create an aliased <code>public.option_group__options</code> table
     * reference
     */
    public OptionGroup_Options(Name alias) {
        this(alias, OPTION_GROUP__OPTIONS);
    }

    /**
     * Create a <code>public.option_group__options</code> table reference
     */
    public OptionGroup_Options() {
        this(DSL.name("option_group__options"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OptionGroup_OptionsRecord> getPrimaryKey() {
        return Keys.PK_OPTION_GROUP__OPTIONS;
    }

    @Override
    public List<ForeignKey<OptionGroup_OptionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OPTION_GROUP__OPTIONS__FK_OPTGROOPT_ON_OPTION, Keys.OPTION_GROUP__OPTIONS__FK_OPTGROOPT_ON_OPTION_GROUP);
    }

    @Override
    public OptionGroup_Options as(String alias) {
        return new OptionGroup_Options(DSL.name(alias), this);
    }

    @Override
    public OptionGroup_Options as(Name alias) {
        return new OptionGroup_Options(alias, this);
    }

    @Override
    public OptionGroup_Options as(Table<?> alias) {
        return new OptionGroup_Options(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OptionGroup_Options rename(String name) {
        return new OptionGroup_Options(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OptionGroup_Options rename(Name name) {
        return new OptionGroup_Options(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OptionGroup_Options rename(Table<?> name) {
        return new OptionGroup_Options(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup_Options where(Condition condition) {
        return new OptionGroup_Options(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup_Options where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup_Options where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup_Options where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroup_Options where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroup_Options where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroup_Options where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OptionGroup_Options where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup_Options whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OptionGroup_Options whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
