/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.OrgUnitGroupMembersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgUnitGroupMembers extends TableImpl<OrgUnitGroupMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.org_unit_group_members</code>
     */
    public static final OrgUnitGroupMembers ORG_UNIT_GROUP_MEMBERS = new OrgUnitGroupMembers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgUnitGroupMembersRecord> getRecordType() {
        return OrgUnitGroupMembersRecord.class;
    }

    /**
     * The column <code>public.org_unit_group_members.group_id</code>.
     */
    public final TableField<OrgUnitGroupMembersRecord, String> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.org_unit_group_members.org_unit_id</code>.
     */
    public final TableField<OrgUnitGroupMembersRecord, String> ORG_UNIT_ID = createField(DSL.name("org_unit_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    private OrgUnitGroupMembers(Name alias, Table<OrgUnitGroupMembersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrgUnitGroupMembers(Name alias, Table<OrgUnitGroupMembersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.org_unit_group_members</code> table
     * reference
     */
    public OrgUnitGroupMembers(String alias) {
        this(DSL.name(alias), ORG_UNIT_GROUP_MEMBERS);
    }

    /**
     * Create an aliased <code>public.org_unit_group_members</code> table
     * reference
     */
    public OrgUnitGroupMembers(Name alias) {
        this(alias, ORG_UNIT_GROUP_MEMBERS);
    }

    /**
     * Create a <code>public.org_unit_group_members</code> table reference
     */
    public OrgUnitGroupMembers() {
        this(DSL.name("org_unit_group_members"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OrgUnitGroupMembersRecord> getPrimaryKey() {
        return Keys.PK_ORG_UNIT_GROUP_MEMBERS;
    }

    @Override
    public List<ForeignKey<OrgUnitGroupMembersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORG_UNIT_GROUP_MEMBERS__FK_ORGUNIGROMEM_ON_ORG_UNIT, Keys.ORG_UNIT_GROUP_MEMBERS__FK_ORGUNIGROMEM_ON_ORG_UNIT_GROUP);
    }

    @Override
    public OrgUnitGroupMembers as(String alias) {
        return new OrgUnitGroupMembers(DSL.name(alias), this);
    }

    @Override
    public OrgUnitGroupMembers as(Name alias) {
        return new OrgUnitGroupMembers(alias, this);
    }

    @Override
    public OrgUnitGroupMembers as(Table<?> alias) {
        return new OrgUnitGroupMembers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitGroupMembers rename(String name) {
        return new OrgUnitGroupMembers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitGroupMembers rename(Name name) {
        return new OrgUnitGroupMembers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitGroupMembers rename(Table<?> name) {
        return new OrgUnitGroupMembers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupMembers where(Condition condition) {
        return new OrgUnitGroupMembers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupMembers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupMembers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupMembers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupMembers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupMembers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupMembers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupMembers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupMembers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupMembers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
