/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.OrgUnitGroupsetRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgUnitGroupset extends TableImpl<OrgUnitGroupsetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.org_unit_groupset</code>
     */
    public static final OrgUnitGroupset ORG_UNIT_GROUPSET = new OrgUnitGroupset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgUnitGroupsetRecord> getRecordType() {
        return OrgUnitGroupsetRecord.class;
    }

    /**
     * The column <code>public.org_unit_groupset.id</code>.
     */
    public final TableField<OrgUnitGroupsetRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.org_unit_groupset.uid</code>.
     */
    public final TableField<OrgUnitGroupsetRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.org_unit_groupset.code</code>.
     */
    public final TableField<OrgUnitGroupsetRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.org_unit_groupset.name</code>.
     */
    public final TableField<OrgUnitGroupsetRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.org_unit_groupset.translations</code>.
     */
    public final TableField<OrgUnitGroupsetRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.org_unit_groupset.created_by</code>.
     */
    public final TableField<OrgUnitGroupsetRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.org_unit_groupset.created_date</code>.
     */
    public final TableField<OrgUnitGroupsetRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.org_unit_groupset.last_modified_by</code>.
     */
    public final TableField<OrgUnitGroupsetRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.org_unit_groupset.last_modified_date</code>.
     */
    public final TableField<OrgUnitGroupsetRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.org_unit_groupset.properties_map</code>.
     */
    public final TableField<OrgUnitGroupsetRecord, JSONB> PROPERTIES_MAP = createField(DSL.name("properties_map"), SQLDataType.JSONB, this, "");

    private OrgUnitGroupset(Name alias, Table<OrgUnitGroupsetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrgUnitGroupset(Name alias, Table<OrgUnitGroupsetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.org_unit_groupset</code> table reference
     */
    public OrgUnitGroupset(String alias) {
        this(DSL.name(alias), ORG_UNIT_GROUPSET);
    }

    /**
     * Create an aliased <code>public.org_unit_groupset</code> table reference
     */
    public OrgUnitGroupset(Name alias) {
        this(alias, ORG_UNIT_GROUPSET);
    }

    /**
     * Create a <code>public.org_unit_groupset</code> table reference
     */
    public OrgUnitGroupset() {
        this(DSL.name("org_unit_groupset"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OrgUnitGroupsetRecord> getPrimaryKey() {
        return Keys.PK_ORG_UNIT_GROUPSET;
    }

    @Override
    public List<UniqueKey<OrgUnitGroupsetRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_ORG_UNIT_GROUPSET_CODE, Keys.UC_ORG_UNIT_GROUPSET_NAME, Keys.UC_ORG_UNIT_GROUPSET_UID);
    }

    @Override
    public OrgUnitGroupset as(String alias) {
        return new OrgUnitGroupset(DSL.name(alias), this);
    }

    @Override
    public OrgUnitGroupset as(Name alias) {
        return new OrgUnitGroupset(alias, this);
    }

    @Override
    public OrgUnitGroupset as(Table<?> alias) {
        return new OrgUnitGroupset(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitGroupset rename(String name) {
        return new OrgUnitGroupset(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitGroupset rename(Name name) {
        return new OrgUnitGroupset(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitGroupset rename(Table<?> name) {
        return new OrgUnitGroupset(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupset where(Condition condition) {
        return new OrgUnitGroupset(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupset where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupset where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupset where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupset where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupset where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupset where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupset where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupset whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupset whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
