/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.OrgUnitGroupsetOrgUnitGroupRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgUnitGroupsetOrgUnitGroup extends TableImpl<OrgUnitGroupsetOrgUnitGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.org_unit_groupset_org_unit_group</code>
     */
    public static final OrgUnitGroupsetOrgUnitGroup ORG_UNIT_GROUPSET_ORG_UNIT_GROUP = new OrgUnitGroupsetOrgUnitGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgUnitGroupsetOrgUnitGroupRecord> getRecordType() {
        return OrgUnitGroupsetOrgUnitGroupRecord.class;
    }

    /**
     * The column
     * <code>public.org_unit_groupset_org_unit_group.groupset_id</code>.
     */
    public final TableField<OrgUnitGroupsetOrgUnitGroupRecord, String> GROUPSET_ID = createField(DSL.name("groupset_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column
     * <code>public.org_unit_groupset_org_unit_group.org_unit_group_id</code>.
     */
    public final TableField<OrgUnitGroupsetOrgUnitGroupRecord, String> ORG_UNIT_GROUP_ID = createField(DSL.name("org_unit_group_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    private OrgUnitGroupsetOrgUnitGroup(Name alias, Table<OrgUnitGroupsetOrgUnitGroupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrgUnitGroupsetOrgUnitGroup(Name alias, Table<OrgUnitGroupsetOrgUnitGroupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.org_unit_groupset_org_unit_group</code>
     * table reference
     */
    public OrgUnitGroupsetOrgUnitGroup(String alias) {
        this(DSL.name(alias), ORG_UNIT_GROUPSET_ORG_UNIT_GROUP);
    }

    /**
     * Create an aliased <code>public.org_unit_groupset_org_unit_group</code>
     * table reference
     */
    public OrgUnitGroupsetOrgUnitGroup(Name alias) {
        this(alias, ORG_UNIT_GROUPSET_ORG_UNIT_GROUP);
    }

    /**
     * Create a <code>public.org_unit_groupset_org_unit_group</code> table
     * reference
     */
    public OrgUnitGroupsetOrgUnitGroup() {
        this(DSL.name("org_unit_groupset_org_unit_group"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OrgUnitGroupsetOrgUnitGroupRecord> getPrimaryKey() {
        return Keys.PK_ORG_UNIT_GROUPSET_ORG_UNIT_GROUP;
    }

    @Override
    public List<ForeignKey<OrgUnitGroupsetOrgUnitGroupRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORG_UNIT_GROUPSET_ORG_UNIT_GROUP__FK_ORGUNIGROORGUNIGRO_ON_ORG_UNIT_GROUP, Keys.ORG_UNIT_GROUPSET_ORG_UNIT_GROUP__FK_ORGUNIGROORGUNIGRO_ON_ORG_UNIT_GROUP_SET);
    }

    @Override
    public OrgUnitGroupsetOrgUnitGroup as(String alias) {
        return new OrgUnitGroupsetOrgUnitGroup(DSL.name(alias), this);
    }

    @Override
    public OrgUnitGroupsetOrgUnitGroup as(Name alias) {
        return new OrgUnitGroupsetOrgUnitGroup(alias, this);
    }

    @Override
    public OrgUnitGroupsetOrgUnitGroup as(Table<?> alias) {
        return new OrgUnitGroupsetOrgUnitGroup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitGroupsetOrgUnitGroup rename(String name) {
        return new OrgUnitGroupsetOrgUnitGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitGroupsetOrgUnitGroup rename(Name name) {
        return new OrgUnitGroupsetOrgUnitGroup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitGroupsetOrgUnitGroup rename(Table<?> name) {
        return new OrgUnitGroupsetOrgUnitGroup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupsetOrgUnitGroup where(Condition condition) {
        return new OrgUnitGroupsetOrgUnitGroup(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupsetOrgUnitGroup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupsetOrgUnitGroup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupsetOrgUnitGroup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupsetOrgUnitGroup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupsetOrgUnitGroup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupsetOrgUnitGroup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitGroupsetOrgUnitGroup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupsetOrgUnitGroup whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitGroupsetOrgUnitGroup whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
