/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Indexes;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.OrgUnitHierarchyRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgUnitHierarchy extends TableImpl<OrgUnitHierarchyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.org_unit_hierarchy</code>
     */
    public static final OrgUnitHierarchy ORG_UNIT_HIERARCHY = new OrgUnitHierarchy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgUnitHierarchyRecord> getRecordType() {
        return OrgUnitHierarchyRecord.class;
    }

    /**
     * The column <code>public.org_unit_hierarchy.ancestor_id</code>.
     */
    public final TableField<OrgUnitHierarchyRecord, String> ANCESTOR_ID = createField(DSL.name("ancestor_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.org_unit_hierarchy.descendant_id</code>.
     */
    public final TableField<OrgUnitHierarchyRecord, String> DESCENDANT_ID = createField(DSL.name("descendant_id"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.org_unit_hierarchy.level_diff</code>.
     */
    public final TableField<OrgUnitHierarchyRecord, Integer> LEVEL_DIFF = createField(DSL.name("level_diff"), SQLDataType.INTEGER, this, "");

    private OrgUnitHierarchy(Name alias, Table<OrgUnitHierarchyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrgUnitHierarchy(Name alias, Table<OrgUnitHierarchyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.org_unit_hierarchy</code> table reference
     */
    public OrgUnitHierarchy(String alias) {
        this(DSL.name(alias), ORG_UNIT_HIERARCHY);
    }

    /**
     * Create an aliased <code>public.org_unit_hierarchy</code> table reference
     */
    public OrgUnitHierarchy(Name alias) {
        this(alias, ORG_UNIT_HIERARCHY);
    }

    /**
     * Create a <code>public.org_unit_hierarchy</code> table reference
     */
    public OrgUnitHierarchy() {
        this(DSL.name("org_unit_hierarchy"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_OUH_ANCESTOR, Indexes.IDX_OUH_DESCENDANT);
    }

    @Override
    public UniqueKey<OrgUnitHierarchyRecord> getPrimaryKey() {
        return Keys.PK_OUH;
    }

    @Override
    public OrgUnitHierarchy as(String alias) {
        return new OrgUnitHierarchy(DSL.name(alias), this);
    }

    @Override
    public OrgUnitHierarchy as(Name alias) {
        return new OrgUnitHierarchy(alias, this);
    }

    @Override
    public OrgUnitHierarchy as(Table<?> alias) {
        return new OrgUnitHierarchy(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitHierarchy rename(String name) {
        return new OrgUnitHierarchy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitHierarchy rename(Name name) {
        return new OrgUnitHierarchy(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnitHierarchy rename(Table<?> name) {
        return new OrgUnitHierarchy(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitHierarchy where(Condition condition) {
        return new OrgUnitHierarchy(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitHierarchy where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitHierarchy where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitHierarchy where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitHierarchy where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitHierarchy where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitHierarchy where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnitHierarchy where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitHierarchy whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnitHierarchy whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
