/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.OuLevelRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OuLevel extends TableImpl<OuLevelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ou_level</code>
     */
    public static final OuLevel OU_LEVEL = new OuLevel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OuLevelRecord> getRecordType() {
        return OuLevelRecord.class;
    }

    /**
     * The column <code>public.ou_level.id</code>.
     */
    public final TableField<OuLevelRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.ou_level.uid</code>.
     */
    public final TableField<OuLevelRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.ou_level.code</code>.
     */
    public final TableField<OuLevelRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.ou_level.name</code>.
     */
    public final TableField<OuLevelRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.ou_level.level</code>.
     */
    public final TableField<OuLevelRecord, Integer> LEVEL = createField(DSL.name("level"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.ou_level.translations</code>.
     */
    public final TableField<OuLevelRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.ou_level.created_by</code>.
     */
    public final TableField<OuLevelRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.ou_level.created_date</code>.
     */
    public final TableField<OuLevelRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.ou_level.last_modified_by</code>.
     */
    public final TableField<OuLevelRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.ou_level.last_modified_date</code>.
     */
    public final TableField<OuLevelRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.ou_level.properties_map</code>.
     */
    public final TableField<OuLevelRecord, JSONB> PROPERTIES_MAP = createField(DSL.name("properties_map"), SQLDataType.JSONB, this, "");

    private OuLevel(Name alias, Table<OuLevelRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OuLevel(Name alias, Table<OuLevelRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ou_level</code> table reference
     */
    public OuLevel(String alias) {
        this(DSL.name(alias), OU_LEVEL);
    }

    /**
     * Create an aliased <code>public.ou_level</code> table reference
     */
    public OuLevel(Name alias) {
        this(alias, OU_LEVEL);
    }

    /**
     * Create a <code>public.ou_level</code> table reference
     */
    public OuLevel() {
        this(DSL.name("ou_level"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OuLevelRecord> getPrimaryKey() {
        return Keys.PK_OU_LEVEL;
    }

    @Override
    public List<UniqueKey<OuLevelRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_OU_LEVEL_CODE, Keys.UC_OU_LEVEL_NAME, Keys.UC_OU_LEVEL_UID);
    }

    @Override
    public OuLevel as(String alias) {
        return new OuLevel(DSL.name(alias), this);
    }

    @Override
    public OuLevel as(Name alias) {
        return new OuLevel(alias, this);
    }

    @Override
    public OuLevel as(Table<?> alias) {
        return new OuLevel(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OuLevel rename(String name) {
        return new OuLevel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OuLevel rename(Name name) {
        return new OuLevel(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OuLevel rename(Table<?> name) {
        return new OuLevel(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OuLevel where(Condition condition) {
        return new OuLevel(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OuLevel where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OuLevel where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OuLevel where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OuLevel where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OuLevel where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OuLevel where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OuLevel where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OuLevel whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OuLevel whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
