/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Indexes;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.PivotGridFactsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PivotGridFacts extends TableImpl<PivotGridFactsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pivot_grid_facts</code>
     */
    public static final PivotGridFacts PIVOT_GRID_FACTS = new PivotGridFacts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PivotGridFactsRecord> getRecordType() {
        return PivotGridFactsRecord.class;
    }

    /**
     * The column <code>public.pivot_grid_facts.value_id</code>.
     */
    public final TableField<PivotGridFactsRecord, Long> VALUE_ID = createField(DSL.name("value_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pivot_grid_facts.submission_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> SUBMISSION_UID = createField(DSL.name("submission_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.pivot_grid_facts.form_template_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> FORM_TEMPLATE_UID = createField(DSL.name("form_template_uid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.pivot_grid_facts.form_version_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> FORM_VERSION_UID = createField(DSL.name("form_version_uid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.pivot_grid_facts.te_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> ETC_UID = createField(DSL.name("te_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.pivot_grid_facts.template_repeat_path</code>.
     */
    public final TableField<PivotGridFactsRecord, String> TEMPLATE_REPEAT_PATH = createField(DSL.name("template_repeat_path"), SQLDataType.VARCHAR(3000), this, "");

    /**
     * The column <code>public.pivot_grid_facts.template_name_path</code>.
     */
    public final TableField<PivotGridFactsRecord, String> TEMPLATE_NAME_PATH = createField(DSL.name("template_name_path"), SQLDataType.VARCHAR(3000), this, "");

    /**
     * The column <code>public.pivot_grid_facts.template_id_path</code>.
     */
    public final TableField<PivotGridFactsRecord, String> TEMPLATE_ID_PATH = createField(DSL.name("template_id_path"), SQLDataType.VARCHAR(3000), this, "");

    /**
     * The column <code>public.pivot_grid_facts.category_element_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> CATEGORY_ELEMENT_UID = createField(DSL.name("category_element_uid"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.pivot_grid_facts.repeat_instance_id</code>.
     */
    public final TableField<PivotGridFactsRecord, String> REPEAT_INSTANCE_ID = createField(DSL.name("repeat_instance_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column
     * <code>public.pivot_grid_facts.parent_repeat_instance_id</code>.
     */
    public final TableField<PivotGridFactsRecord, String> PARENT_REPEAT_INSTANCE_ID = createField(DSL.name("parent_repeat_instance_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.pivot_grid_facts.repeat_path</code>.
     */
    public final TableField<PivotGridFactsRecord, String> REPEAT_PATH = createField(DSL.name("repeat_path"), SQLDataType.VARCHAR(3000), this, "");

    /**
     * The column <code>public.pivot_grid_facts.repeat_section_label</code>.
     */
    public final TableField<PivotGridFactsRecord, JSONB> REPEAT_SECTION_LABEL = createField(DSL.name("repeat_section_label"), SQLDataType.JSONB, this, "");

    /**
     * The column
     * <code>public.pivot_grid_facts.parent_repeat_section_label</code>.
     */
    public final TableField<PivotGridFactsRecord, JSONB> PARENT_REPEAT_SECTION_LABEL = createField(DSL.name("parent_repeat_section_label"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.pivot_grid_facts.assignment_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> ASSIGNMENT_UID = createField(DSL.name("assignment_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.pivot_grid_facts.team_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> TEAM_UID = createField(DSL.name("team_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.pivot_grid_facts.team_code</code>.
     */
    public final TableField<PivotGridFactsRecord, String> TEAM_CODE = createField(DSL.name("team_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.pivot_grid_facts.org_unit_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> ORG_UNIT_UID = createField(DSL.name("org_unit_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.pivot_grid_facts.org_unit_name</code>.
     */
    public final TableField<PivotGridFactsRecord, String> ORG_UNIT_NAME = createField(DSL.name("org_unit_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.pivot_grid_facts.org_unit_code</code>.
     */
    public final TableField<PivotGridFactsRecord, String> ORG_UNIT_CODE = createField(DSL.name("org_unit_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.pivot_grid_facts.activity_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> ACTIVITY_UID = createField(DSL.name("activity_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.pivot_grid_facts.activity_name</code>.
     */
    public final TableField<PivotGridFactsRecord, String> ACTIVITY_NAME = createField(DSL.name("activity_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.pivot_grid_facts.submission_completed_at</code>.
     */
    public final TableField<PivotGridFactsRecord, LocalDateTime> SUBMISSION_COMPLETED_AT = createField(DSL.name("submission_completed_at"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>public.pivot_grid_facts.child_category_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> CHILD_CATEGORY_UID = createField(DSL.name("child_category_uid"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.pivot_grid_facts.parent_category_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> PARENT_CATEGORY_UID = createField(DSL.name("parent_category_uid"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.pivot_grid_facts.child_category_kind</code>.
     */
    public final TableField<PivotGridFactsRecord, String> CHILD_CATEGORY_KIND = createField(DSL.name("child_category_kind"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.pivot_grid_facts.parent_category_kind</code>.
     */
    public final TableField<PivotGridFactsRecord, String> PARENT_CATEGORY_KIND = createField(DSL.name("parent_category_kind"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.pivot_grid_facts.display_label</code>.
     */
    public final TableField<PivotGridFactsRecord, JSONB> DISPLAY_LABEL = createField(DSL.name("display_label"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.pivot_grid_facts.category_id</code>.
     */
    public final TableField<PivotGridFactsRecord, String> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.pivot_grid_facts.de_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> DE_UID = createField(DSL.name("de_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.pivot_grid_facts.de_name</code>.
     */
    public final TableField<PivotGridFactsRecord, String> DE_NAME = createField(DSL.name("de_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.pivot_grid_facts.de_value_type</code>.
     */
    public final TableField<PivotGridFactsRecord, String> DE_VALUE_TYPE = createField(DSL.name("de_value_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.pivot_grid_facts.de_option_set_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> DE_OPTION_SET_UID = createField(DSL.name("de_option_set_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.pivot_grid_facts.option_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> OPTION_UID = createField(DSL.name("option_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.pivot_grid_facts.option_value_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> OPTION_VALUE_UID = createField(DSL.name("option_value_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.pivot_grid_facts.option_name</code>.
     */
    public final TableField<PivotGridFactsRecord, String> OPTION_NAME = createField(DSL.name("option_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.pivot_grid_facts.option_code</code>.
     */
    public final TableField<PivotGridFactsRecord, String> OPTION_CODE = createField(DSL.name("option_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.pivot_grid_facts.child_category_name</code>.
     */
    public final TableField<PivotGridFactsRecord, String> CHILD_CATEGORY_NAME = createField(DSL.name("child_category_name"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.pivot_grid_facts.parent_category_name</code>.
     */
    public final TableField<PivotGridFactsRecord, String> PARENT_CATEGORY_NAME = createField(DSL.name("parent_category_name"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.pivot_grid_facts.value_num</code>.
     */
    public final TableField<PivotGridFactsRecord, BigDecimal> VALUE_NUM = createField(DSL.name("value_num"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.pivot_grid_facts.value_text</code>.
     */
    public final TableField<PivotGridFactsRecord, String> VALUE_TEXT = createField(DSL.name("value_text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.pivot_grid_facts.value_bool</code>.
     */
    public final TableField<PivotGridFactsRecord, Boolean> VALUE_BOOL = createField(DSL.name("value_bool"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.pivot_grid_facts.value_ts</code>.
     */
    public final TableField<PivotGridFactsRecord, LocalDateTime> VALUE_TS = createField(DSL.name("value_ts"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>public.pivot_grid_facts.value_ref_uid</code>.
     */
    public final TableField<PivotGridFactsRecord, String> VALUE_REF_UID = createField(DSL.name("value_ref_uid"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.pivot_grid_facts.deleted_at</code>.
     */
    public final TableField<PivotGridFactsRecord, LocalDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.LOCALDATETIME(0), this, "");

    private PivotGridFacts(Name alias, Table<PivotGridFactsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PivotGridFacts(Name alias, Table<PivotGridFactsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.materializedView(), where);
    }

    /**
     * Create an aliased <code>public.pivot_grid_facts</code> table reference
     */
    public PivotGridFacts(String alias) {
        this(DSL.name(alias), PIVOT_GRID_FACTS);
    }

    /**
     * Create an aliased <code>public.pivot_grid_facts</code> table reference
     */
    public PivotGridFacts(Name alias) {
        this(alias, PIVOT_GRID_FACTS);
    }

    /**
     * Create a <code>public.pivot_grid_facts</code> table reference
     */
    public PivotGridFacts() {
        this(DSL.name("pivot_grid_facts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PIVOT_FACTS_ACTIVITY_UID, Indexes.IDX_PIVOT_FACTS_CHILD_CATEGORY_UID, Indexes.IDX_PIVOT_FACTS_ELEMENT_UID, Indexes.IDX_PIVOT_FACTS_ETC_UID, Indexes.IDX_PIVOT_FACTS_OPTION_UID, Indexes.IDX_PIVOT_FACTS_ORG_UNIT_UID, Indexes.IDX_PIVOT_FACTS_PARENT_CATEGORY_UID, Indexes.IDX_PIVOT_FACTS_TEAM_UID, Indexes.IDX_PIVOT_FACTS_TIME, Indexes.UX_PIVOT_GRID_FACTS__UNIQUE);
    }

    @Override
    public PivotGridFacts as(String alias) {
        return new PivotGridFacts(DSL.name(alias), this);
    }

    @Override
    public PivotGridFacts as(Name alias) {
        return new PivotGridFacts(alias, this);
    }

    @Override
    public PivotGridFacts as(Table<?> alias) {
        return new PivotGridFacts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PivotGridFacts rename(String name) {
        return new PivotGridFacts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PivotGridFacts rename(Name name) {
        return new PivotGridFacts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PivotGridFacts rename(Table<?> name) {
        return new PivotGridFacts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PivotGridFacts where(Condition condition) {
        return new PivotGridFacts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PivotGridFacts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PivotGridFacts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PivotGridFacts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PivotGridFacts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PivotGridFacts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PivotGridFacts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PivotGridFacts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PivotGridFacts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PivotGridFacts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
