/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Indexes;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.RepeatInstanceRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RepeatInstance extends TableImpl<RepeatInstanceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.repeat_instance</code>
     */
    public static final RepeatInstance REPEAT_INSTANCE = new RepeatInstance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RepeatInstanceRecord> getRecordType() {
        return RepeatInstanceRecord.class;
    }

    /**
     * The column <code>public.repeat_instance.id</code>.
     */
    public final TableField<RepeatInstanceRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.repeat_instance.semantic_path</code>.
     */
    public final TableField<RepeatInstanceRecord, String> SEMANTIC_PATH = createField(DSL.name("semantic_path"), SQLDataType.VARCHAR(3000).nullable(false), this, "");

    /**
     * The column <code>public.repeat_instance.parent_repeat_instance_id</code>.
     */
    public final TableField<RepeatInstanceRecord, String> PARENT_REPEAT_INSTANCE_ID = createField(DSL.name("parent_repeat_instance_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.repeat_instance.repeat_section_label</code>.
     */
    public final TableField<RepeatInstanceRecord, JSONB> REPEAT_SECTION_LABEL = createField(DSL.name("repeat_section_label"), SQLDataType.JSONB.defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.repeat_instance.submission_uid</code>.
     */
    public final TableField<RepeatInstanceRecord, String> SUBMISSION_UID = createField(DSL.name("submission_uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.repeat_instance.category_kind</code>.
     */
    public final TableField<RepeatInstanceRecord, String> CATEGORY_KIND = createField(DSL.name("category_kind"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.repeat_instance.category_uid</code>.
     */
    public final TableField<RepeatInstanceRecord, String> CATEGORY_UID = createField(DSL.name("category_uid"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.repeat_instance.category_name</code>.
     */
    public final TableField<RepeatInstanceRecord, String> CATEGORY_NAME = createField(DSL.name("category_name"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.repeat_instance.category_label</code>.
     */
    public final TableField<RepeatInstanceRecord, JSONB> CATEGORY_LABEL = createField(DSL.name("category_label"), SQLDataType.JSONB.defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.repeat_instance.repeat_path</code>.
     */
    public final TableField<RepeatInstanceRecord, String> REPEAT_PATH = createField(DSL.name("repeat_path"), SQLDataType.VARCHAR(3000).nullable(false), this, "");

    /**
     * The column <code>public.repeat_instance.repeat_index</code>.
     */
    public final TableField<RepeatInstanceRecord, Long> REPEAT_INDEX = createField(DSL.name("repeat_index"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.repeat_instance.client_updated_at</code>.
     */
    public final TableField<RepeatInstanceRecord, LocalDateTime> CLIENT_UPDATED_AT = createField(DSL.name("client_updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.repeat_instance.deleted_at</code>.
     */
    public final TableField<RepeatInstanceRecord, LocalDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.repeat_instance.submission_completed_at</code>.
     */
    public final TableField<RepeatInstanceRecord, LocalDateTime> SUBMISSION_COMPLETED_AT = createField(DSL.name("submission_completed_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.repeat_instance.created_date</code>.
     */
    public final TableField<RepeatInstanceRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.repeat_instance.last_modified_date</code>.
     */
    public final TableField<RepeatInstanceRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.repeat_instance.last_modified_by</code>.
     */
    public final TableField<RepeatInstanceRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.repeat_instance.created_by</code>.
     */
    public final TableField<RepeatInstanceRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "");

    private RepeatInstance(Name alias, Table<RepeatInstanceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RepeatInstance(Name alias, Table<RepeatInstanceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.repeat_instance</code> table reference
     */
    public RepeatInstance(String alias) {
        this(DSL.name(alias), REPEAT_INSTANCE);
    }

    /**
     * Create an aliased <code>public.repeat_instance</code> table reference
     */
    public RepeatInstance(Name alias) {
        this(alias, REPEAT_INSTANCE);
    }

    /**
     * Create a <code>public.repeat_instance</code> table reference
     */
    public RepeatInstance() {
        this(DSL.name("repeat_instance"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REPEAT_INSTANCE_PARENT_ID, Indexes.IDX_REPEAT_INSTANCE_SUBMISSION_PATH);
    }

    @Override
    public UniqueKey<RepeatInstanceRecord> getPrimaryKey() {
        return Keys.REPEAT_INSTANCE_PKEY;
    }

    @Override
    public List<ForeignKey<RepeatInstanceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REPEAT_INSTANCE__FK_REPEAT_INSTANCE_PARENT);
    }

    @Override
    public RepeatInstance as(String alias) {
        return new RepeatInstance(DSL.name(alias), this);
    }

    @Override
    public RepeatInstance as(Name alias) {
        return new RepeatInstance(alias, this);
    }

    @Override
    public RepeatInstance as(Table<?> alias) {
        return new RepeatInstance(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RepeatInstance rename(String name) {
        return new RepeatInstance(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RepeatInstance rename(Name name) {
        return new RepeatInstance(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RepeatInstance rename(Table<?> name) {
        return new RepeatInstance(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RepeatInstance where(Condition condition) {
        return new RepeatInstance(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RepeatInstance where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RepeatInstance where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RepeatInstance where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RepeatInstance where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RepeatInstance where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RepeatInstance where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RepeatInstance where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RepeatInstance whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RepeatInstance whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
