/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.RolePrivilegeMembersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePrivilegeMembers extends TableImpl<RolePrivilegeMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.role_privilege_members</code>
     */
    public static final RolePrivilegeMembers ROLE_PRIVILEGE_MEMBERS = new RolePrivilegeMembers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RolePrivilegeMembersRecord> getRecordType() {
        return RolePrivilegeMembersRecord.class;
    }

    /**
     * The column <code>public.role_privilege_members.privilege_id</code>.
     */
    public final TableField<RolePrivilegeMembersRecord, String> PRIVILEGE_ID = createField(DSL.name("privilege_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.role_privilege_members.role_id</code>.
     */
    public final TableField<RolePrivilegeMembersRecord, String> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    private RolePrivilegeMembers(Name alias, Table<RolePrivilegeMembersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RolePrivilegeMembers(Name alias, Table<RolePrivilegeMembersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.role_privilege_members</code> table
     * reference
     */
    public RolePrivilegeMembers(String alias) {
        this(DSL.name(alias), ROLE_PRIVILEGE_MEMBERS);
    }

    /**
     * Create an aliased <code>public.role_privilege_members</code> table
     * reference
     */
    public RolePrivilegeMembers(Name alias) {
        this(alias, ROLE_PRIVILEGE_MEMBERS);
    }

    /**
     * Create a <code>public.role_privilege_members</code> table reference
     */
    public RolePrivilegeMembers() {
        this(DSL.name("role_privilege_members"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<RolePrivilegeMembersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ROLE_PRIVILEGE_MEMBERS__FK_ROLPRIMEM_ON_PRIVILEGE, Keys.ROLE_PRIVILEGE_MEMBERS__FK_ROLPRIMEM_ON_ROLE);
    }

    @Override
    public RolePrivilegeMembers as(String alias) {
        return new RolePrivilegeMembers(DSL.name(alias), this);
    }

    @Override
    public RolePrivilegeMembers as(Name alias) {
        return new RolePrivilegeMembers(alias, this);
    }

    @Override
    public RolePrivilegeMembers as(Table<?> alias) {
        return new RolePrivilegeMembers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RolePrivilegeMembers rename(String name) {
        return new RolePrivilegeMembers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RolePrivilegeMembers rename(Name name) {
        return new RolePrivilegeMembers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RolePrivilegeMembers rename(Table<?> name) {
        return new RolePrivilegeMembers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RolePrivilegeMembers where(Condition condition) {
        return new RolePrivilegeMembers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RolePrivilegeMembers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RolePrivilegeMembers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RolePrivilegeMembers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RolePrivilegeMembers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RolePrivilegeMembers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RolePrivilegeMembers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RolePrivilegeMembers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RolePrivilegeMembers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RolePrivilegeMembers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
