/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.Keys;
import org.nmcpye.datarun.jooq.Public;
import org.nmcpye.datarun.jooq.tables.records.TeamManagedTeamsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamManagedTeams extends TableImpl<TeamManagedTeamsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.team_managed_teams</code>
     */
    public static final TeamManagedTeams TEAM_MANAGED_TEAMS = new TeamManagedTeams();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamManagedTeamsRecord> getRecordType() {
        return TeamManagedTeamsRecord.class;
    }

    /**
     * The column <code>public.team_managed_teams.managed_team_id</code>.
     */
    public final TableField<TeamManagedTeamsRecord, String> MANAGED_TEAM_ID = createField(DSL.name("managed_team_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.team_managed_teams.team_id</code>.
     */
    public final TableField<TeamManagedTeamsRecord, String> TEAM_ID = createField(DSL.name("team_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    private TeamManagedTeams(Name alias, Table<TeamManagedTeamsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TeamManagedTeams(Name alias, Table<TeamManagedTeamsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.team_managed_teams</code> table reference
     */
    public TeamManagedTeams(String alias) {
        this(DSL.name(alias), TEAM_MANAGED_TEAMS);
    }

    /**
     * Create an aliased <code>public.team_managed_teams</code> table reference
     */
    public TeamManagedTeams(Name alias) {
        this(alias, TEAM_MANAGED_TEAMS);
    }

    /**
     * Create a <code>public.team_managed_teams</code> table reference
     */
    public TeamManagedTeams() {
        this(DSL.name("team_managed_teams"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TeamManagedTeamsRecord> getPrimaryKey() {
        return Keys.PK_TEAM_MANAGED_TEAMS;
    }

    @Override
    public List<ForeignKey<TeamManagedTeamsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TEAM_MANAGED_TEAMS__FK_TEAMANTEA_ON_MANAGED_TEAM, Keys.TEAM_MANAGED_TEAMS__FK_TEAMANTEA_ON_TEAM);
    }

    @Override
    public TeamManagedTeams as(String alias) {
        return new TeamManagedTeams(DSL.name(alias), this);
    }

    @Override
    public TeamManagedTeams as(Name alias) {
        return new TeamManagedTeams(alias, this);
    }

    @Override
    public TeamManagedTeams as(Table<?> alias) {
        return new TeamManagedTeams(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamManagedTeams rename(String name) {
        return new TeamManagedTeams(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamManagedTeams rename(Name name) {
        return new TeamManagedTeams(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamManagedTeams rename(Table<?> name) {
        return new TeamManagedTeams(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamManagedTeams where(Condition condition) {
        return new TeamManagedTeams(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamManagedTeams where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamManagedTeams where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamManagedTeams where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamManagedTeams where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamManagedTeams where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamManagedTeams where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamManagedTeams where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamManagedTeams whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamManagedTeams whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
