/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.nmcpye.datarun.jooq.tables.AppEntityAuditEvent;
import org.nmcpye.datarun.jooq.tables.DataSubmission;
import org.nmcpye.datarun.jooq.tables.DataTemplateVersion;
import org.nmcpye.datarun.jooq.tables.ElementDataValue;
import org.nmcpye.datarun.jooq.tables.ElementTemplateConfig;
import org.nmcpye.datarun.jooq.tables.MigrationErrors;
import org.nmcpye.datarun.jooq.tables.OrgUnitHierarchy;
import org.nmcpye.datarun.jooq.tables.OutboxEvent;
import org.nmcpye.datarun.jooq.tables.PivotGridFacts;
import org.nmcpye.datarun.jooq.tables.RefreshToken;
import org.nmcpye.datarun.jooq.tables.RepeatInstance;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_DS_ACTIVE_FORM_ASSIGNMENT = Internal.createIndex(DSL.name("idx_ds_active_form_assignment"), DataSubmission.DATA_SUBMISSION, new OrderField[] { DataSubmission.DATA_SUBMISSION.TEMPLATE_UID, DataSubmission.DATA_SUBMISSION.ASSIGNMENT_UID }, false);
    public static final Index IDX_DS_FORM_ASSIGNMENT = Internal.createIndex(DSL.name("idx_ds_form_assignment"), DataSubmission.DATA_SUBMISSION, new OrderField[] { DataSubmission.DATA_SUBMISSION.TEMPLATE_VERSION_UID, DataSubmission.DATA_SUBMISSION.ASSIGNMENT_UID }, false);
    public static final Index IDX_DS_FORM_DATA_GIN = Internal.createIndex(DSL.name("idx_ds_form_data_gin"), DataSubmission.DATA_SUBMISSION, new OrderField[] { DataSubmission.DATA_SUBMISSION.FORM_DATA }, false);
    public static final Index IDX_DS_ORGUNIT = Internal.createIndex(DSL.name("idx_ds_orgunit"), DataSubmission.DATA_SUBMISSION, new OrderField[] { DataSubmission.DATA_SUBMISSION.ORG_UNIT_UID }, false);
    public static final Index IDX_DS_SERIAL_NUMBER = Internal.createIndex(DSL.name("idx_ds_serial_number"), DataSubmission.DATA_SUBMISSION, new OrderField[] { DataSubmission.DATA_SUBMISSION.SERIAL_NUMBER }, false);
    public static final Index IDX_EDV_ELEMENT_ACTIVE = Internal.createIndex(DSL.name("idx_edv_element_active"), ElementDataValue.ELEMENT_DATA_VALUE, new OrderField[] { ElementDataValue.ELEMENT_DATA_VALUE.ELEMENT_UID }, false);
    public static final Index IDX_EDV_TEAM_ACTIVE = Internal.createIndex(DSL.name("idx_edv_team_active"), ElementDataValue.ELEMENT_DATA_VALUE, new OrderField[] { ElementDataValue.ELEMENT_DATA_VALUE.TEAM_UID }, false);
    public static final Index IDX_ELEMENT_DATA_VALUE_SUBMISSION_REPEAT = Internal.createIndex(DSL.name("idx_element_data_value_submission_repeat"), ElementDataValue.ELEMENT_DATA_VALUE, new OrderField[] { ElementDataValue.ELEMENT_DATA_VALUE.SUBMISSION_UID, ElementDataValue.ELEMENT_DATA_VALUE.REPEAT_INSTANCE_ID }, false);
    public static final Index IDX_ELEMENT_TEMPLATE_CONFIG_DATAELEMENT = Internal.createIndex(DSL.name("idx_element_template_config_dataelement"), ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG, new OrderField[] { ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG.DATA_ELEMENT_UID }, false);
    public static final Index IDX_ELEMENT_TEMPLATE_CONFIG_REPEAT_PATH = Internal.createIndex(DSL.name("idx_element_template_config_repeat_path"), ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG, new OrderField[] { ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG.TEMPLATE_UID, ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG.ANCESTOR_REPEAT_PATH }, false);
    public static final Index IDX_ELEMENT_TEMPLATE_CONFIG_TEMPLATE_VERSION = Internal.createIndex(DSL.name("idx_element_template_config_template_version"), ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG, new OrderField[] { ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG.TEMPLATE_UID, ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG.TEMPLATE_VERSION_UID }, false);
    public static final Index IDX_ELEMENT_TEMPLATE_CONFIG_TEMPLATE_VERSION_NO = Internal.createIndex(DSL.name("idx_element_template_config_template_version_no"), ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG, new OrderField[] { ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG.TEMPLATE_UID, ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG.TEMPLATE_VERSION_NO }, false);
    public static final Index IDX_ENTITY_AUDIT_EVENT_ENTITY_TYPE = Internal.createIndex(DSL.name("idx_entity_audit_event_entity_type"), AppEntityAuditEvent.APP_ENTITY_AUDIT_EVENT, new OrderField[] { AppEntityAuditEvent.APP_ENTITY_AUDIT_EVENT.ENTITY_TYPE }, false);
    public static final Index IDX_MIGRATION_ERRORS_SOURCE = Internal.createIndex(DSL.name("idx_migration_errors_source"), MigrationErrors.MIGRATION_ERRORS, new OrderField[] { MigrationErrors.MIGRATION_ERRORS.SOURCE_ID }, false);
    public static final Index IDX_MIGRATION_ERRORS_STAGE = Internal.createIndex(DSL.name("idx_migration_errors_stage"), MigrationErrors.MIGRATION_ERRORS, new OrderField[] { MigrationErrors.MIGRATION_ERRORS.STAGE }, false);
    public static final Index IDX_MIGRATION_ERRORS_SUBMISSION = Internal.createIndex(DSL.name("idx_migration_errors_submission"), MigrationErrors.MIGRATION_ERRORS, new OrderField[] { MigrationErrors.MIGRATION_ERRORS.SUBMISSION_UID }, false);
    public static final Index IDX_OUH_ANCESTOR = Internal.createIndex(DSL.name("idx_ouh_ancestor"), OrgUnitHierarchy.ORG_UNIT_HIERARCHY, new OrderField[] { OrgUnitHierarchy.ORG_UNIT_HIERARCHY.ANCESTOR_ID }, false);
    public static final Index IDX_OUH_DESCENDANT = Internal.createIndex(DSL.name("idx_ouh_descendant"), OrgUnitHierarchy.ORG_UNIT_HIERARCHY, new OrderField[] { OrgUnitHierarchy.ORG_UNIT_HIERARCHY.DESCENDANT_ID }, false);
    public static final Index IDX_OUTBOX_AGGREGATE = Internal.createIndex(DSL.name("idx_outbox_aggregate"), OutboxEvent.OUTBOX_EVENT, new OrderField[] { OutboxEvent.OUTBOX_EVENT.AGGREGATE_TYPE, OutboxEvent.OUTBOX_EVENT.AGGREGATE_ID }, false);
    public static final Index IDX_OUTBOX_STATUS_AVAILABLE = Internal.createIndex(DSL.name("idx_outbox_status_available"), OutboxEvent.OUTBOX_EVENT, new OrderField[] { OutboxEvent.OUTBOX_EVENT.STATUS, OutboxEvent.OUTBOX_EVENT.AVAILABLE_AT }, false);
    public static final Index IDX_PIVOT_FACTS_ACTIVITY_UID = Internal.createIndex(DSL.name("idx_pivot_facts_activity_uid"), PivotGridFacts.PIVOT_GRID_FACTS, new OrderField[] { PivotGridFacts.PIVOT_GRID_FACTS.ACTIVITY_UID }, false);
    public static final Index IDX_PIVOT_FACTS_CHILD_CATEGORY_UID = Internal.createIndex(DSL.name("idx_pivot_facts_child_category_uid"), PivotGridFacts.PIVOT_GRID_FACTS, new OrderField[] { PivotGridFacts.PIVOT_GRID_FACTS.CHILD_CATEGORY_UID }, false);
    public static final Index IDX_PIVOT_FACTS_ELEMENT_UID = Internal.createIndex(DSL.name("idx_pivot_facts_element_uid"), PivotGridFacts.PIVOT_GRID_FACTS, new OrderField[] { PivotGridFacts.PIVOT_GRID_FACTS.DE_UID }, false);
    public static final Index IDX_PIVOT_FACTS_ETC_UID = Internal.createIndex(DSL.name("idx_pivot_facts_etc_uid"), PivotGridFacts.PIVOT_GRID_FACTS, new OrderField[] { PivotGridFacts.PIVOT_GRID_FACTS.ETC_UID }, false);
    public static final Index IDX_PIVOT_FACTS_OPTION_UID = Internal.createIndex(DSL.name("idx_pivot_facts_option_uid"), PivotGridFacts.PIVOT_GRID_FACTS, new OrderField[] { PivotGridFacts.PIVOT_GRID_FACTS.OPTION_UID }, false);
    public static final Index IDX_PIVOT_FACTS_ORG_UNIT_UID = Internal.createIndex(DSL.name("idx_pivot_facts_org_unit_uid"), PivotGridFacts.PIVOT_GRID_FACTS, new OrderField[] { PivotGridFacts.PIVOT_GRID_FACTS.ORG_UNIT_UID }, false);
    public static final Index IDX_PIVOT_FACTS_PARENT_CATEGORY_UID = Internal.createIndex(DSL.name("idx_pivot_facts_parent_category_uid"), PivotGridFacts.PIVOT_GRID_FACTS, new OrderField[] { PivotGridFacts.PIVOT_GRID_FACTS.PARENT_CATEGORY_UID }, false);
    public static final Index IDX_PIVOT_FACTS_TEAM_UID = Internal.createIndex(DSL.name("idx_pivot_facts_team_uid"), PivotGridFacts.PIVOT_GRID_FACTS, new OrderField[] { PivotGridFacts.PIVOT_GRID_FACTS.TEAM_UID }, false);
    public static final Index IDX_PIVOT_FACTS_TIME = Internal.createIndex(DSL.name("idx_pivot_facts_time"), PivotGridFacts.PIVOT_GRID_FACTS, new OrderField[] { PivotGridFacts.PIVOT_GRID_FACTS.SUBMISSION_COMPLETED_AT }, false);
    public static final Index IDX_REFRESH_TOKEN_TOKEN_UNQ = Internal.createIndex(DSL.name("idx_refresh_token_token_unq"), RefreshToken.REFRESH_TOKEN, new OrderField[] { RefreshToken.REFRESH_TOKEN.TOKEN }, true);
    public static final Index IDX_REPEAT_INSTANCE_PARENT_ID = Internal.createIndex(DSL.name("idx_repeat_instance_parent_id"), RepeatInstance.REPEAT_INSTANCE, new OrderField[] { RepeatInstance.REPEAT_INSTANCE.PARENT_REPEAT_INSTANCE_ID }, false);
    public static final Index IDX_REPEAT_INSTANCE_SUBMISSION_PATH = Internal.createIndex(DSL.name("idx_repeat_instance_submission_path"), RepeatInstance.REPEAT_INSTANCE, new OrderField[] { RepeatInstance.REPEAT_INSTANCE.SUBMISSION_UID, RepeatInstance.REPEAT_INSTANCE.REPEAT_PATH }, false);
    public static final Index IDX_TV_TEMPLATE_UID = Internal.createIndex(DSL.name("idx_tv_template_uid"), DataTemplateVersion.DATA_TEMPLATE_VERSION, new OrderField[] { DataTemplateVersion.DATA_TEMPLATE_VERSION.TEMPLATE_UID }, false);
    public static final Index IDX_TV_TEMPLATE_UID_VERSION_DESC = Internal.createIndex(DSL.name("idx_tv_template_uid_version_desc"), DataTemplateVersion.DATA_TEMPLATE_VERSION, new OrderField[] { DataTemplateVersion.DATA_TEMPLATE_VERSION.TEMPLATE_UID, DataTemplateVersion.DATA_TEMPLATE_VERSION.VERSION_NUMBER }, false);
    public static final Index IDX_TV_VERSION_NO = Internal.createIndex(DSL.name("idx_tv_version_no"), DataTemplateVersion.DATA_TEMPLATE_VERSION, new OrderField[] { DataTemplateVersion.DATA_TEMPLATE_VERSION.VERSION_NUMBER }, false);
    public static final Index UX_ELEMENT_VALUE_UNIQUE = Internal.createIndex(DSL.name("ux_element_value_unique"), ElementDataValue.ELEMENT_DATA_VALUE, new OrderField[] { ElementDataValue.ELEMENT_DATA_VALUE.SUBMISSION_UID, ElementDataValue.ELEMENT_DATA_VALUE.ELEMENT_UID, ElementDataValue.ELEMENT_DATA_VALUE.REPEAT_INSTANCE_KEY, ElementDataValue.ELEMENT_DATA_VALUE.ROW_TYPE, ElementDataValue.ELEMENT_DATA_VALUE.SELECTION_KEY }, true);
    public static final Index UX_PIVOT_GRID_FACTS__UNIQUE = Internal.createIndex(DSL.name("ux_pivot_grid_facts__unique"), PivotGridFacts.PIVOT_GRID_FACTS, new OrderField[] { PivotGridFacts.PIVOT_GRID_FACTS.SUBMISSION_UID, PivotGridFacts.PIVOT_GRID_FACTS.ETC_UID, PivotGridFacts.PIVOT_GRID_FACTS.REPEAT_INSTANCE_ID, PivotGridFacts.PIVOT_GRID_FACTS.OPTION_UID }, true);
}
