/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq;


import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.nmcpye.datarun.jooq.tables.*;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.acl_class</code>.
     */
    public final AclClass ACL_CLASS = AclClass.ACL_CLASS;

    /**
     * The table <code>public.acl_entry</code>.
     */
    public final AclEntry ACL_ENTRY = AclEntry.ACL_ENTRY;

    /**
     * The table <code>public.acl_object_identity</code>.
     */
    public final AclObjectIdentity ACL_OBJECT_IDENTITY = AclObjectIdentity.ACL_OBJECT_IDENTITY;

    /**
     * The table <code>public.acl_sid</code>.
     */
    public final AclSid ACL_SID = AclSid.ACL_SID;

    /**
     * The table <code>public.activity</code>.
     */
    public final Activity ACTIVITY = Activity.ACTIVITY;

    /**
     * The table <code>public.app_authority</code>.
     */
    public final AppAuthority APP_AUTHORITY = AppAuthority.APP_AUTHORITY;

    /**
     * The table <code>public.app_entity_audit_event</code>.
     */
    public final AppEntityAuditEvent APP_ENTITY_AUDIT_EVENT = AppEntityAuditEvent.APP_ENTITY_AUDIT_EVENT;

    /**
     * The table <code>public.app_user</code>.
     */
    public final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.app_user_authority</code>.
     */
    public final AppUserAuthority APP_USER_AUTHORITY = AppUserAuthority.APP_USER_AUTHORITY;

    /**
     * The table <code>public.app_user_role_members</code>.
     */
    public final AppUserRoleMembers APP_USER_ROLE_MEMBERS = AppUserRoleMembers.APP_USER_ROLE_MEMBERS;

    /**
     * The table <code>public.assignment</code>.
     */
    public final Assignment ASSIGNMENT = Assignment.ASSIGNMENT;

    /**
     * The table <code>public.batch_job_execution</code>.
     */
    public final BatchJobExecution BATCH_JOB_EXECUTION = BatchJobExecution.BATCH_JOB_EXECUTION;

    /**
     * The table <code>public.batch_job_execution_context</code>.
     */
    public final BatchJobExecutionContext BATCH_JOB_EXECUTION_CONTEXT = BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT;

    /**
     * The table <code>public.batch_job_execution_params</code>.
     */
    public final BatchJobExecutionParams BATCH_JOB_EXECUTION_PARAMS = BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS;

    /**
     * The table <code>public.batch_job_instance</code>.
     */
    public final BatchJobInstance BATCH_JOB_INSTANCE = BatchJobInstance.BATCH_JOB_INSTANCE;

    /**
     * The table <code>public.batch_step_execution</code>.
     */
    public final BatchStepExecution BATCH_STEP_EXECUTION = BatchStepExecution.BATCH_STEP_EXECUTION;

    /**
     * The table <code>public.batch_step_execution_context</code>.
     */
    public final BatchStepExecutionContext BATCH_STEP_EXECUTION_CONTEXT = BatchStepExecutionContext.BATCH_STEP_EXECUTION_CONTEXT;

    /**
     * The table <code>public.data_element</code>.
     */
    public final DataElement DATA_ELEMENT = DataElement.DATA_ELEMENT;

    /**
     * The table <code>public.data_element_group</code>.
     */
    public final DataElementGroup DATA_ELEMENT_GROUP = DataElementGroup.DATA_ELEMENT_GROUP;

    /**
     * The table <code>public.data_element_group_members</code>.
     */
    public final DataElementGroupMembers DATA_ELEMENT_GROUP_MEMBERS = DataElementGroupMembers.DATA_ELEMENT_GROUP_MEMBERS;

    /**
     * The table <code>public.data_element_groupset</code>.
     */
    public final DataElementGroupset DATA_ELEMENT_GROUPSET = DataElementGroupset.DATA_ELEMENT_GROUPSET;

    /**
     * The table <code>public.data_element_groupset_groups</code>.
     */
    public final DataElementGroupsetGroups DATA_ELEMENT_GROUPSET_GROUPS = DataElementGroupsetGroups.DATA_ELEMENT_GROUPSET_GROUPS;

    /**
     * The table <code>public.data_submission</code>.
     */
    public final DataSubmission DATA_SUBMISSION = DataSubmission.DATA_SUBMISSION;

    /**
     * The table <code>public.data_template</code>.
     */
    public final DataTemplate DATA_TEMPLATE = DataTemplate.DATA_TEMPLATE;

    /**
     * The table <code>public.data_template_version</code>.
     */
    public final DataTemplateVersion DATA_TEMPLATE_VERSION = DataTemplateVersion.DATA_TEMPLATE_VERSION;

    /**
     * The table <code>public.element_data_value</code>.
     */
    public final ElementDataValue ELEMENT_DATA_VALUE = ElementDataValue.ELEMENT_DATA_VALUE;

    /**
     * The table <code>public.template_element</code>.
     */
    public final ElementTemplateConfig ELEMENT_TEMPLATE_CONFIG = ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG;

    /**
     * The table <code>public.migration_errors</code>.
     */
    public final MigrationErrors MIGRATION_ERRORS = MigrationErrors.MIGRATION_ERRORS;

    /**
     * The table <code>public.option_group</code>.
     */
    public final OptionGroup OPTION_GROUP = OptionGroup.OPTION_GROUP;

    /**
     * The table <code>public.option_group__options</code>.
     */
    public final OptionGroup_Options OPTION_GROUP__OPTIONS = OptionGroup_Options.OPTION_GROUP__OPTIONS;

    /**
     * The table <code>public.option_group_set</code>.
     */
    public final OptionGroupSet OPTION_GROUP_SET = OptionGroupSet.OPTION_GROUP_SET;

    /**
     * The table <code>public.option_groupset__option_group</code>.
     */
    public final OptionGroupset_OptionGroup OPTION_GROUPSET__OPTION_GROUP = OptionGroupset_OptionGroup.OPTION_GROUPSET__OPTION_GROUP;

    /**
     * The table <code>public.option_set</code>.
     */
    public final OptionSet OPTION_SET = OptionSet.OPTION_SET;

    /**
     * The table <code>public.option_value</code>.
     */
    public final OptionValue OPTION_VALUE = OptionValue.OPTION_VALUE;

    /**
     * The table <code>public.org_unit</code>.
     */
    public final OrgUnit ORG_UNIT = OrgUnit.ORG_UNIT;

    /**
     * The table <code>public.org_unit_group</code>.
     */
    public final OrgUnitGroup ORG_UNIT_GROUP = OrgUnitGroup.ORG_UNIT_GROUP;

    /**
     * The table <code>public.org_unit_group_members</code>.
     */
    public final OrgUnitGroupMembers ORG_UNIT_GROUP_MEMBERS = OrgUnitGroupMembers.ORG_UNIT_GROUP_MEMBERS;

    /**
     * The table <code>public.org_unit_groupset</code>.
     */
    public final OrgUnitGroupset ORG_UNIT_GROUPSET = OrgUnitGroupset.ORG_UNIT_GROUPSET;

    /**
     * The table <code>public.org_unit_groupset_org_unit_group</code>.
     */
    public final OrgUnitGroupsetOrgUnitGroup ORG_UNIT_GROUPSET_ORG_UNIT_GROUP = OrgUnitGroupsetOrgUnitGroup.ORG_UNIT_GROUPSET_ORG_UNIT_GROUP;

    /**
     * The table <code>public.org_unit_hierarchy</code>.
     */
    public final OrgUnitHierarchy ORG_UNIT_HIERARCHY = OrgUnitHierarchy.ORG_UNIT_HIERARCHY;

    /**
     * The table <code>public.ou_level</code>.
     */
    public final OuLevel OU_LEVEL = OuLevel.OU_LEVEL;

    /**
     * The table <code>public.outbox_event</code>.
     */
    public final OutboxEvent OUTBOX_EVENT = OutboxEvent.OUTBOX_EVENT;

    /**
     * The table <code>public.pivot_grid_facts</code>.
     */
    public final PivotGridFacts PIVOT_GRID_FACTS = PivotGridFacts.PIVOT_GRID_FACTS;

    /**
     * The table <code>public.project</code>.
     */
    public final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>public.refresh_token</code>.
     */
    public final RefreshToken REFRESH_TOKEN = RefreshToken.REFRESH_TOKEN;

    /**
     * The table <code>public.repeat_instance</code>.
     */
    public final RepeatInstance REPEAT_INSTANCE = RepeatInstance.REPEAT_INSTANCE;

    /**
     * The table <code>public.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.role_privilege</code>.
     */
    public final RolePrivilege ROLE_PRIVILEGE = RolePrivilege.ROLE_PRIVILEGE;

    /**
     * The table <code>public.role_privilege_members</code>.
     */
    public final RolePrivilegeMembers ROLE_PRIVILEGE_MEMBERS = RolePrivilegeMembers.ROLE_PRIVILEGE_MEMBERS;

    /**
     * The table <code>public.team</code>.
     */
    public final Team TEAM = Team.TEAM;

    /**
     * The table <code>public.team_managed_teams</code>.
     */
    public final TeamManagedTeams TEAM_MANAGED_TEAMS = TeamManagedTeams.TEAM_MANAGED_TEAMS;

    /**
     * The table <code>public.team_user</code>.
     */
    public final TeamUser TEAM_USER = TeamUser.TEAM_USER;

    /**
     * The table <code>public.user_group</code>.
     */
    public final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    /**
     * The table <code>public.user_group_managed_groups</code>.
     */
    public final UserGroupManagedGroups USER_GROUP_MANAGED_GROUPS = UserGroupManagedGroups.USER_GROUP_MANAGED_GROUPS;

    /**
     * The table <code>public.user_group_users</code>.
     */
    public final UserGroupUsers USER_GROUP_USERS = UserGroupUsers.USER_GROUP_USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.BATCH_JOB_EXECUTION_SEQ,
            Sequences.BATCH_JOB_SEQ,
            Sequences.BATCH_STEP_EXECUTION_SEQ,
            Sequences.ELEMENT_TEMPLATE_CONFIG_SEQ,
            Sequences.SEQUENCE_GENERATOR,
            Sequences.SUBMISSION_SERIAL_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AclClass.ACL_CLASS,
            AclEntry.ACL_ENTRY,
            AclObjectIdentity.ACL_OBJECT_IDENTITY,
            AclSid.ACL_SID,
            Activity.ACTIVITY,
            AppAuthority.APP_AUTHORITY,
            AppEntityAuditEvent.APP_ENTITY_AUDIT_EVENT,
            AppUser.APP_USER,
            AppUserAuthority.APP_USER_AUTHORITY,
            AppUserRoleMembers.APP_USER_ROLE_MEMBERS,
            Assignment.ASSIGNMENT,
            BatchJobExecution.BATCH_JOB_EXECUTION,
            BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT,
            BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS,
            BatchJobInstance.BATCH_JOB_INSTANCE,
            BatchStepExecution.BATCH_STEP_EXECUTION,
            BatchStepExecutionContext.BATCH_STEP_EXECUTION_CONTEXT,
            DataElement.DATA_ELEMENT,
            DataElementGroup.DATA_ELEMENT_GROUP,
            DataElementGroupMembers.DATA_ELEMENT_GROUP_MEMBERS,
            DataElementGroupset.DATA_ELEMENT_GROUPSET,
            DataElementGroupsetGroups.DATA_ELEMENT_GROUPSET_GROUPS,
            DataSubmission.DATA_SUBMISSION,
            DataTemplate.DATA_TEMPLATE,
            DataTemplateVersion.DATA_TEMPLATE_VERSION,
            ElementDataValue.ELEMENT_DATA_VALUE,
            ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG,
            MigrationErrors.MIGRATION_ERRORS,
            OptionGroup.OPTION_GROUP,
            OptionGroup_Options.OPTION_GROUP__OPTIONS,
            OptionGroupSet.OPTION_GROUP_SET,
            OptionGroupset_OptionGroup.OPTION_GROUPSET__OPTION_GROUP,
            OptionSet.OPTION_SET,
            OptionValue.OPTION_VALUE,
            OrgUnit.ORG_UNIT,
            OrgUnitGroup.ORG_UNIT_GROUP,
            OrgUnitGroupMembers.ORG_UNIT_GROUP_MEMBERS,
            OrgUnitGroupset.ORG_UNIT_GROUPSET,
            OrgUnitGroupsetOrgUnitGroup.ORG_UNIT_GROUPSET_ORG_UNIT_GROUP,
            OrgUnitHierarchy.ORG_UNIT_HIERARCHY,
            OuLevel.OU_LEVEL,
            OutboxEvent.OUTBOX_EVENT,
            PivotGridFacts.PIVOT_GRID_FACTS,
            Project.PROJECT,
            RefreshToken.REFRESH_TOKEN,
            RepeatInstance.REPEAT_INSTANCE,
            Role.ROLE,
            RolePrivilege.ROLE_PRIVILEGE,
            RolePrivilegeMembers.ROLE_PRIVILEGE_MEMBERS,
            Team.TEAM,
            TeamManagedTeams.TEAM_MANAGED_TEAMS,
            TeamUser.TEAM_USER,
            UserGroup.USER_GROUP,
            UserGroupManagedGroups.USER_GROUP_MANAGED_GROUPS,
            UserGroupUsers.USER_GROUP_USERS
        );
    }
}
