/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq;


import org.jooq.Configuration;
import org.jooq.Field;
import org.nmcpye.datarun.jooq.routines.GenerateUid;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.generate_uid</code>
     */
    public static String generateUid(
          Configuration configuration
    ) {
        GenerateUid f = new GenerateUid();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.generate_uid</code> as a field.
     */
    public static Field<String> generateUid() {
        GenerateUid f = new GenerateUid();

        return f.asField();
    }
}
