/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq;


import org.nmcpye.datarun.jooq.tables.AclClass;
import org.nmcpye.datarun.jooq.tables.AclEntry;
import org.nmcpye.datarun.jooq.tables.AclObjectIdentity;
import org.nmcpye.datarun.jooq.tables.AclSid;
import org.nmcpye.datarun.jooq.tables.Activity;
import org.nmcpye.datarun.jooq.tables.AppAuthority;
import org.nmcpye.datarun.jooq.tables.AppEntityAuditEvent;
import org.nmcpye.datarun.jooq.tables.AppUser;
import org.nmcpye.datarun.jooq.tables.AppUserAuthority;
import org.nmcpye.datarun.jooq.tables.AppUserRoleMembers;
import org.nmcpye.datarun.jooq.tables.Assignment;
import org.nmcpye.datarun.jooq.tables.BatchJobExecution;
import org.nmcpye.datarun.jooq.tables.BatchJobExecutionContext;
import org.nmcpye.datarun.jooq.tables.BatchJobExecutionParams;
import org.nmcpye.datarun.jooq.tables.BatchJobInstance;
import org.nmcpye.datarun.jooq.tables.BatchStepExecution;
import org.nmcpye.datarun.jooq.tables.BatchStepExecutionContext;
import org.nmcpye.datarun.jooq.tables.DataElement;
import org.nmcpye.datarun.jooq.tables.DataElementGroup;
import org.nmcpye.datarun.jooq.tables.DataElementGroupMembers;
import org.nmcpye.datarun.jooq.tables.DataElementGroupset;
import org.nmcpye.datarun.jooq.tables.DataElementGroupsetGroups;
import org.nmcpye.datarun.jooq.tables.DataSubmission;
import org.nmcpye.datarun.jooq.tables.DataTemplate;
import org.nmcpye.datarun.jooq.tables.DataTemplateVersion;
import org.nmcpye.datarun.jooq.tables.ElementDataValue;
import org.nmcpye.datarun.jooq.tables.ElementTemplateConfig;
import org.nmcpye.datarun.jooq.tables.MigrationErrors;
import org.nmcpye.datarun.jooq.tables.OptionGroup;
import org.nmcpye.datarun.jooq.tables.OptionGroupSet;
import org.nmcpye.datarun.jooq.tables.OptionGroup_Options;
import org.nmcpye.datarun.jooq.tables.OptionGroupset_OptionGroup;
import org.nmcpye.datarun.jooq.tables.OptionSet;
import org.nmcpye.datarun.jooq.tables.OptionValue;
import org.nmcpye.datarun.jooq.tables.OrgUnit;
import org.nmcpye.datarun.jooq.tables.OrgUnitGroup;
import org.nmcpye.datarun.jooq.tables.OrgUnitGroupMembers;
import org.nmcpye.datarun.jooq.tables.OrgUnitGroupset;
import org.nmcpye.datarun.jooq.tables.OrgUnitGroupsetOrgUnitGroup;
import org.nmcpye.datarun.jooq.tables.OrgUnitHierarchy;
import org.nmcpye.datarun.jooq.tables.OuLevel;
import org.nmcpye.datarun.jooq.tables.OutboxEvent;
import org.nmcpye.datarun.jooq.tables.PivotGridFacts;
import org.nmcpye.datarun.jooq.tables.Project;
import org.nmcpye.datarun.jooq.tables.RefreshToken;
import org.nmcpye.datarun.jooq.tables.RepeatInstance;
import org.nmcpye.datarun.jooq.tables.Role;
import org.nmcpye.datarun.jooq.tables.RolePrivilege;
import org.nmcpye.datarun.jooq.tables.RolePrivilegeMembers;
import org.nmcpye.datarun.jooq.tables.Team;
import org.nmcpye.datarun.jooq.tables.TeamManagedTeams;
import org.nmcpye.datarun.jooq.tables.TeamUser;
import org.nmcpye.datarun.jooq.tables.UserGroup;
import org.nmcpye.datarun.jooq.tables.UserGroupManagedGroups;
import org.nmcpye.datarun.jooq.tables.UserGroupUsers;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.acl_class</code>.
     */
    public static final AclClass ACL_CLASS = AclClass.ACL_CLASS;

    /**
     * The table <code>public.acl_entry</code>.
     */
    public static final AclEntry ACL_ENTRY = AclEntry.ACL_ENTRY;

    /**
     * The table <code>public.acl_object_identity</code>.
     */
    public static final AclObjectIdentity ACL_OBJECT_IDENTITY = AclObjectIdentity.ACL_OBJECT_IDENTITY;

    /**
     * The table <code>public.acl_sid</code>.
     */
    public static final AclSid ACL_SID = AclSid.ACL_SID;

    /**
     * The table <code>public.activity</code>.
     */
    public static final Activity ACTIVITY = Activity.ACTIVITY;

    /**
     * The table <code>public.app_authority</code>.
     */
    public static final AppAuthority APP_AUTHORITY = AppAuthority.APP_AUTHORITY;

    /**
     * The table <code>public.app_entity_audit_event</code>.
     */
    public static final AppEntityAuditEvent APP_ENTITY_AUDIT_EVENT = AppEntityAuditEvent.APP_ENTITY_AUDIT_EVENT;

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.app_user_authority</code>.
     */
    public static final AppUserAuthority APP_USER_AUTHORITY = AppUserAuthority.APP_USER_AUTHORITY;

    /**
     * The table <code>public.app_user_role_members</code>.
     */
    public static final AppUserRoleMembers APP_USER_ROLE_MEMBERS = AppUserRoleMembers.APP_USER_ROLE_MEMBERS;

    /**
     * The table <code>public.assignment</code>.
     */
    public static final Assignment ASSIGNMENT = Assignment.ASSIGNMENT;

    /**
     * The table <code>public.batch_job_execution</code>.
     */
    public static final BatchJobExecution BATCH_JOB_EXECUTION = BatchJobExecution.BATCH_JOB_EXECUTION;

    /**
     * The table <code>public.batch_job_execution_context</code>.
     */
    public static final BatchJobExecutionContext BATCH_JOB_EXECUTION_CONTEXT = BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT;

    /**
     * The table <code>public.batch_job_execution_params</code>.
     */
    public static final BatchJobExecutionParams BATCH_JOB_EXECUTION_PARAMS = BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS;

    /**
     * The table <code>public.batch_job_instance</code>.
     */
    public static final BatchJobInstance BATCH_JOB_INSTANCE = BatchJobInstance.BATCH_JOB_INSTANCE;

    /**
     * The table <code>public.batch_step_execution</code>.
     */
    public static final BatchStepExecution BATCH_STEP_EXECUTION = BatchStepExecution.BATCH_STEP_EXECUTION;

    /**
     * The table <code>public.batch_step_execution_context</code>.
     */
    public static final BatchStepExecutionContext BATCH_STEP_EXECUTION_CONTEXT = BatchStepExecutionContext.BATCH_STEP_EXECUTION_CONTEXT;

    /**
     * The table <code>public.data_element</code>.
     */
    public static final DataElement DATA_ELEMENT = DataElement.DATA_ELEMENT;

    /**
     * The table <code>public.data_element_group</code>.
     */
    public static final DataElementGroup DATA_ELEMENT_GROUP = DataElementGroup.DATA_ELEMENT_GROUP;

    /**
     * The table <code>public.data_element_group_members</code>.
     */
    public static final DataElementGroupMembers DATA_ELEMENT_GROUP_MEMBERS = DataElementGroupMembers.DATA_ELEMENT_GROUP_MEMBERS;

    /**
     * The table <code>public.data_element_groupset</code>.
     */
    public static final DataElementGroupset DATA_ELEMENT_GROUPSET = DataElementGroupset.DATA_ELEMENT_GROUPSET;

    /**
     * The table <code>public.data_element_groupset_groups</code>.
     */
    public static final DataElementGroupsetGroups DATA_ELEMENT_GROUPSET_GROUPS = DataElementGroupsetGroups.DATA_ELEMENT_GROUPSET_GROUPS;

    /**
     * The table <code>public.data_submission</code>.
     */
    public static final DataSubmission DATA_SUBMISSION = DataSubmission.DATA_SUBMISSION;

    /**
     * The table <code>public.data_template</code>.
     */
    public static final DataTemplate DATA_TEMPLATE = DataTemplate.DATA_TEMPLATE;

    /**
     * The table <code>public.data_template_version</code>.
     */
    public static final DataTemplateVersion DATA_TEMPLATE_VERSION = DataTemplateVersion.DATA_TEMPLATE_VERSION;

    /**
     * The table <code>public.element_data_value</code>.
     */
    public static final ElementDataValue ELEMENT_DATA_VALUE = ElementDataValue.ELEMENT_DATA_VALUE;

    /**
     * The table <code>public.element_template_config</code>.
     */
    public static final ElementTemplateConfig ELEMENT_TEMPLATE_CONFIG = ElementTemplateConfig.ELEMENT_TEMPLATE_CONFIG;

    /**
     * The table <code>public.migration_errors</code>.
     */
    public static final MigrationErrors MIGRATION_ERRORS = MigrationErrors.MIGRATION_ERRORS;

    /**
     * The table <code>public.option_group</code>.
     */
    public static final OptionGroup OPTION_GROUP = OptionGroup.OPTION_GROUP;

    /**
     * The table <code>public.option_group__options</code>.
     */
    public static final OptionGroup_Options OPTION_GROUP__OPTIONS = OptionGroup_Options.OPTION_GROUP__OPTIONS;

    /**
     * The table <code>public.option_group_set</code>.
     */
    public static final OptionGroupSet OPTION_GROUP_SET = OptionGroupSet.OPTION_GROUP_SET;

    /**
     * The table <code>public.option_groupset__option_group</code>.
     */
    public static final OptionGroupset_OptionGroup OPTION_GROUPSET__OPTION_GROUP = OptionGroupset_OptionGroup.OPTION_GROUPSET__OPTION_GROUP;

    /**
     * The table <code>public.option_set</code>.
     */
    public static final OptionSet OPTION_SET = OptionSet.OPTION_SET;

    /**
     * The table <code>public.option_value</code>.
     */
    public static final OptionValue OPTION_VALUE = OptionValue.OPTION_VALUE;

    /**
     * The table <code>public.org_unit</code>.
     */
    public static final OrgUnit ORG_UNIT = OrgUnit.ORG_UNIT;

    /**
     * The table <code>public.org_unit_group</code>.
     */
    public static final OrgUnitGroup ORG_UNIT_GROUP = OrgUnitGroup.ORG_UNIT_GROUP;

    /**
     * The table <code>public.org_unit_group_members</code>.
     */
    public static final OrgUnitGroupMembers ORG_UNIT_GROUP_MEMBERS = OrgUnitGroupMembers.ORG_UNIT_GROUP_MEMBERS;

    /**
     * The table <code>public.org_unit_groupset</code>.
     */
    public static final OrgUnitGroupset ORG_UNIT_GROUPSET = OrgUnitGroupset.ORG_UNIT_GROUPSET;

    /**
     * The table <code>public.org_unit_groupset_org_unit_group</code>.
     */
    public static final OrgUnitGroupsetOrgUnitGroup ORG_UNIT_GROUPSET_ORG_UNIT_GROUP = OrgUnitGroupsetOrgUnitGroup.ORG_UNIT_GROUPSET_ORG_UNIT_GROUP;

    /**
     * The table <code>public.org_unit_hierarchy</code>.
     */
    public static final OrgUnitHierarchy ORG_UNIT_HIERARCHY = OrgUnitHierarchy.ORG_UNIT_HIERARCHY;

    /**
     * The table <code>public.ou_level</code>.
     */
    public static final OuLevel OU_LEVEL = OuLevel.OU_LEVEL;

    /**
     * The table <code>public.outbox_event</code>.
     */
    public static final OutboxEvent OUTBOX_EVENT = OutboxEvent.OUTBOX_EVENT;

    /**
     * The table <code>public.pivot_grid_facts</code>.
     */
    public static final PivotGridFacts PIVOT_GRID_FACTS = PivotGridFacts.PIVOT_GRID_FACTS;

    /**
     * The table <code>public.project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>public.refresh_token</code>.
     */
    public static final RefreshToken REFRESH_TOKEN = RefreshToken.REFRESH_TOKEN;

    /**
     * The table <code>public.repeat_instance</code>.
     */
    public static final RepeatInstance REPEAT_INSTANCE = RepeatInstance.REPEAT_INSTANCE;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.role_privilege</code>.
     */
    public static final RolePrivilege ROLE_PRIVILEGE = RolePrivilege.ROLE_PRIVILEGE;

    /**
     * The table <code>public.role_privilege_members</code>.
     */
    public static final RolePrivilegeMembers ROLE_PRIVILEGE_MEMBERS = RolePrivilegeMembers.ROLE_PRIVILEGE_MEMBERS;

    /**
     * The table <code>public.team</code>.
     */
    public static final Team TEAM = Team.TEAM;

    /**
     * The table <code>public.team_managed_teams</code>.
     */
    public static final TeamManagedTeams TEAM_MANAGED_TEAMS = TeamManagedTeams.TEAM_MANAGED_TEAMS;

    /**
     * The table <code>public.team_user</code>.
     */
    public static final TeamUser TEAM_USER = TeamUser.TEAM_USER;

    /**
     * The table <code>public.user_group</code>.
     */
    public static final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    /**
     * The table <code>public.user_group_managed_groups</code>.
     */
    public static final UserGroupManagedGroups USER_GROUP_MANAGED_GROUPS = UserGroupManagedGroups.USER_GROUP_MANAGED_GROUPS;

    /**
     * The table <code>public.user_group_users</code>.
     */
    public static final UserGroupUsers USER_GROUP_USERS = UserGroupUsers.USER_GROUP_USERS;
}
