/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.AclClass;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclClassRecord extends UpdatableRecordImpl<AclClassRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.acl_class.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.acl_class.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.acl_class.class</code>.
     */
    public void setClass_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.acl_class.class</code>.
     */
    public String getClass_() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AclClassRecord
     */
    public AclClassRecord() {
        super(AclClass.ACL_CLASS);
    }

    /**
     * Create a detached, initialised AclClassRecord
     */
    public AclClassRecord(Long id, String class_) {
        super(AclClass.ACL_CLASS);

        setId(id);
        setClass_(class_);
        resetChangedOnNotNull();
    }
}
