/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.AclEntry;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclEntryRecord extends UpdatableRecordImpl<AclEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.acl_entry.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.acl_entry.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.acl_entry.acl_object_identity</code>.
     */
    public void setAclObjectIdentity(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.acl_entry.acl_object_identity</code>.
     */
    public Long getAclObjectIdentity() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.acl_entry.ace_order</code>.
     */
    public void setAceOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.acl_entry.ace_order</code>.
     */
    public Integer getAceOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.acl_entry.sid</code>.
     */
    public void setSid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.acl_entry.sid</code>.
     */
    public Long getSid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.acl_entry.mask</code>.
     */
    public void setMask(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.acl_entry.mask</code>.
     */
    public Integer getMask() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.acl_entry.granting</code>.
     */
    public void setGranting(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.acl_entry.granting</code>.
     */
    public Boolean getGranting() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.acl_entry.audit_success</code>.
     */
    public void setAuditSuccess(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.acl_entry.audit_success</code>.
     */
    public Boolean getAuditSuccess() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.acl_entry.audit_failure</code>.
     */
    public void setAuditFailure(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.acl_entry.audit_failure</code>.
     */
    public Boolean getAuditFailure() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AclEntryRecord
     */
    public AclEntryRecord() {
        super(AclEntry.ACL_ENTRY);
    }

    /**
     * Create a detached, initialised AclEntryRecord
     */
    public AclEntryRecord(Long id, Long aclObjectIdentity, Integer aceOrder, Long sid, Integer mask, Boolean granting, Boolean auditSuccess, Boolean auditFailure) {
        super(AclEntry.ACL_ENTRY);

        setId(id);
        setAclObjectIdentity(aclObjectIdentity);
        setAceOrder(aceOrder);
        setSid(sid);
        setMask(mask);
        setGranting(granting);
        setAuditSuccess(auditSuccess);
        setAuditFailure(auditFailure);
        resetChangedOnNotNull();
    }
}
