/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.AclObjectIdentity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclObjectIdentityRecord extends UpdatableRecordImpl<AclObjectIdentityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.acl_object_identity.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.acl_object_identity.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.acl_object_identity.object_id_class</code>.
     */
    public void setObjectIdClass(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.acl_object_identity.object_id_class</code>.
     */
    public Long getObjectIdClass() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.acl_object_identity.object_id_identity</code>.
     */
    public void setObjectIdIdentity(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.acl_object_identity.object_id_identity</code>.
     */
    public Long getObjectIdIdentity() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.acl_object_identity.parent_object</code>.
     */
    public void setParentObject(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.acl_object_identity.parent_object</code>.
     */
    public Long getParentObject() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.acl_object_identity.owner_sid</code>.
     */
    public void setOwnerSid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.acl_object_identity.owner_sid</code>.
     */
    public Long getOwnerSid() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.acl_object_identity.entries_inheriting</code>.
     */
    public void setEntriesInheriting(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.acl_object_identity.entries_inheriting</code>.
     */
    public Boolean getEntriesInheriting() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AclObjectIdentityRecord
     */
    public AclObjectIdentityRecord() {
        super(AclObjectIdentity.ACL_OBJECT_IDENTITY);
    }

    /**
     * Create a detached, initialised AclObjectIdentityRecord
     */
    public AclObjectIdentityRecord(Long id, Long objectIdClass, Long objectIdIdentity, Long parentObject, Long ownerSid, Boolean entriesInheriting) {
        super(AclObjectIdentity.ACL_OBJECT_IDENTITY);

        setId(id);
        setObjectIdClass(objectIdClass);
        setObjectIdIdentity(objectIdIdentity);
        setParentObject(parentObject);
        setOwnerSid(ownerSid);
        setEntriesInheriting(entriesInheriting);
        resetChangedOnNotNull();
    }
}
