/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.AppAuthority;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppAuthorityRecord extends UpdatableRecordImpl<AppAuthorityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_authority.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_authority.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppAuthorityRecord
     */
    public AppAuthorityRecord() {
        super(AppAuthority.APP_AUTHORITY);
    }

    /**
     * Create a detached, initialised AppAuthorityRecord
     */
    public AppAuthorityRecord(String name) {
        super(AppAuthority.APP_AUTHORITY);

        setName(name);
        resetChangedOnNotNull();
    }
}
