/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.AppUserAuthority;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserAuthorityRecord extends UpdatableRecordImpl<AppUserAuthorityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_user_authority.user_id</code>.
     */
    public void setUserId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_user_authority.user_id</code>.
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_user_authority.authority_name</code>.
     */
    public void setAuthorityName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_user_authority.authority_name</code>.
     */
    public String getAuthorityName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserAuthorityRecord
     */
    public AppUserAuthorityRecord() {
        super(AppUserAuthority.APP_USER_AUTHORITY);
    }

    /**
     * Create a detached, initialised AppUserAuthorityRecord
     */
    public AppUserAuthorityRecord(String userId, String authorityName) {
        super(AppUserAuthority.APP_USER_AUTHORITY);

        setUserId(userId);
        setAuthorityName(authorityName);
        resetChangedOnNotNull();
    }
}
