/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.BatchJobExecution;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobExecutionRecord extends UpdatableRecordImpl<BatchJobExecutionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.batch_job_execution.job_execution_id</code>.
     */
    public void setJobExecutionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.batch_job_execution.job_execution_id</code>.
     */
    public Long getJobExecutionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.batch_job_execution.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.batch_job_execution.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.batch_job_execution.job_instance_id</code>.
     */
    public void setJobInstanceId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.batch_job_execution.job_instance_id</code>.
     */
    public Long getJobInstanceId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.batch_job_execution.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.batch_job_execution.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.batch_job_execution.start_time</code>.
     */
    public void setStartTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.batch_job_execution.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.batch_job_execution.end_time</code>.
     */
    public void setEndTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.batch_job_execution.end_time</code>.
     */
    public LocalDateTime getEndTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.batch_job_execution.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.batch_job_execution.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.batch_job_execution.exit_code</code>.
     */
    public void setExitCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.batch_job_execution.exit_code</code>.
     */
    public String getExitCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.batch_job_execution.exit_message</code>.
     */
    public void setExitMessage(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.batch_job_execution.exit_message</code>.
     */
    public String getExitMessage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.batch_job_execution.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.batch_job_execution.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchJobExecutionRecord
     */
    public BatchJobExecutionRecord() {
        super(BatchJobExecution.BATCH_JOB_EXECUTION);
    }

    /**
     * Create a detached, initialised BatchJobExecutionRecord
     */
    public BatchJobExecutionRecord(Long jobExecutionId, Long version, Long jobInstanceId, LocalDateTime createTime, LocalDateTime startTime, LocalDateTime endTime, String status, String exitCode, String exitMessage, LocalDateTime lastUpdated) {
        super(BatchJobExecution.BATCH_JOB_EXECUTION);

        setJobExecutionId(jobExecutionId);
        setVersion(version);
        setJobInstanceId(jobInstanceId);
        setCreateTime(createTime);
        setStartTime(startTime);
        setEndTime(endTime);
        setStatus(status);
        setExitCode(exitCode);
        setExitMessage(exitMessage);
        setLastUpdated(lastUpdated);
        resetChangedOnNotNull();
    }
}
