/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;
import org.nmcpye.datarun.jooq.tables.BatchJobExecutionParams;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobExecutionParamsRecord extends TableRecordImpl<BatchJobExecutionParamsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.batch_job_execution_params.job_execution_id</code>.
     */
    public void setJobExecutionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.batch_job_execution_params.job_execution_id</code>.
     */
    public Long getJobExecutionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.batch_job_execution_params.parameter_name</code>.
     */
    public void setParameterName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.batch_job_execution_params.parameter_name</code>.
     */
    public String getParameterName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.batch_job_execution_params.parameter_type</code>.
     */
    public void setParameterType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.batch_job_execution_params.parameter_type</code>.
     */
    public String getParameterType() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public.batch_job_execution_params.parameter_value</code>.
     */
    public void setParameterValue(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.batch_job_execution_params.parameter_value</code>.
     */
    public String getParameterValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.batch_job_execution_params.identifying</code>.
     */
    public void setIdentifying(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.batch_job_execution_params.identifying</code>.
     */
    public String getIdentifying() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchJobExecutionParamsRecord
     */
    public BatchJobExecutionParamsRecord() {
        super(BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS);
    }

    /**
     * Create a detached, initialised BatchJobExecutionParamsRecord
     */
    public BatchJobExecutionParamsRecord(Long jobExecutionId, String parameterName, String parameterType, String parameterValue, String identifying) {
        super(BatchJobExecutionParams.BATCH_JOB_EXECUTION_PARAMS);

        setJobExecutionId(jobExecutionId);
        setParameterName(parameterName);
        setParameterType(parameterType);
        setParameterValue(parameterValue);
        setIdentifying(identifying);
        resetChangedOnNotNull();
    }
}
