/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.BatchJobInstance;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobInstanceRecord extends UpdatableRecordImpl<BatchJobInstanceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.batch_job_instance.job_instance_id</code>.
     */
    public void setJobInstanceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.batch_job_instance.job_instance_id</code>.
     */
    public Long getJobInstanceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.batch_job_instance.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.batch_job_instance.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.batch_job_instance.job_name</code>.
     */
    public void setJobName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.batch_job_instance.job_name</code>.
     */
    public String getJobName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.batch_job_instance.job_key</code>.
     */
    public void setJobKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.batch_job_instance.job_key</code>.
     */
    public String getJobKey() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchJobInstanceRecord
     */
    public BatchJobInstanceRecord() {
        super(BatchJobInstance.BATCH_JOB_INSTANCE);
    }

    /**
     * Create a detached, initialised BatchJobInstanceRecord
     */
    public BatchJobInstanceRecord(Long jobInstanceId, Long version, String jobName, String jobKey) {
        super(BatchJobInstance.BATCH_JOB_INSTANCE);

        setJobInstanceId(jobInstanceId);
        setVersion(version);
        setJobName(jobName);
        setJobKey(jobKey);
        resetChangedOnNotNull();
    }
}
