/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.BatchJobExecutionContext;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchJobExecutionContextRecord extends UpdatableRecordImpl<BatchJobExecutionContextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.batch_job_execution_context.job_execution_id</code>.
     */
    public void setJobExecutionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.batch_job_execution_context.job_execution_id</code>.
     */
    public Long getJobExecutionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.batch_job_execution_context.short_context</code>.
     */
    public void setShortContext(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.batch_job_execution_context.short_context</code>.
     */
    public String getShortContext() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>public.batch_job_execution_context.serialized_context</code>.
     */
    public void setSerializedContext(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.batch_job_execution_context.serialized_context</code>.
     */
    public String getSerializedContext() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchJobExecutionContextRecord
     */
    public BatchJobExecutionContextRecord() {
        super(BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT);
    }

    /**
     * Create a detached, initialised BatchJobExecutionContextRecord
     */
    public BatchJobExecutionContextRecord(Long jobExecutionId, String shortContext, String serializedContext) {
        super(BatchJobExecutionContext.BATCH_JOB_EXECUTION_CONTEXT);

        setJobExecutionId(jobExecutionId);
        setShortContext(shortContext);
        setSerializedContext(serializedContext);
        resetChangedOnNotNull();
    }
}
