/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.DataElementGroupMembers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataElementGroupMembersRecord extends UpdatableRecordImpl<DataElementGroupMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.data_element_group_members.group_id</code>.
     */
    public void setGroupId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.data_element_group_members.group_id</code>.
     */
    public String getGroupId() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>public.data_element_group_members.data_element_id</code>.
     */
    public void setDataElementId(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.data_element_group_members.data_element_id</code>.
     */
    public String getDataElementId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataElementGroupMembersRecord
     */
    public DataElementGroupMembersRecord() {
        super(DataElementGroupMembers.DATA_ELEMENT_GROUP_MEMBERS);
    }

    /**
     * Create a detached, initialised DataElementGroupMembersRecord
     */
    public DataElementGroupMembersRecord(String groupId, String dataElementId) {
        super(DataElementGroupMembers.DATA_ELEMENT_GROUP_MEMBERS);

        setGroupId(groupId);
        setDataElementId(dataElementId);
        resetChangedOnNotNull();
    }
}
