/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.DataElement;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataElementRecord extends UpdatableRecordImpl<DataElementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.data_element.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.data_element.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.data_element.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.data_element.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.data_element.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.data_element.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.data_element.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.data_element.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.data_element.short_name</code>.
     */
    public void setShortName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.data_element.short_name</code>.
     */
    public String getShortName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.data_element.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.data_element.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.data_element.type</code>.
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.data_element.type</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.data_element.option_set_id</code>.
     */
    public void setOptionSetId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.data_element.option_set_id</code>.
     */
    public String getOptionSetId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.data_element.reference_type</code>.
     */
    public void setReferenceType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.data_element.reference_type</code>.
     */
    public String getReferenceType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.data_element.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.data_element.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(9);
    }

    /**
     * Setter for <code>public.data_element.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.data_element.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.data_element.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.data_element.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.data_element.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.data_element.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.data_element.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.data_element.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.data_element.is_measure</code>.
     */
    public void setIsMeasure(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.data_element.is_measure</code>.
     */
    public Boolean getIsMeasure() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.data_element.aggregation_type</code>.
     */
    public void setAggregationType(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.data_element.aggregation_type</code>.
     */
    public String getAggregationType() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.data_element.is_dimension</code>.
     */
    public void setIsDimension(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.data_element.is_dimension</code>.
     */
    public Boolean getIsDimension() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>public.data_element.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.data_element.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataElementRecord
     */
    public DataElementRecord() {
        super(DataElement.DATA_ELEMENT);
    }

    /**
     * Create a detached, initialised DataElementRecord
     */
    public DataElementRecord(String id, String uid, String code, String name, String shortName, String description, String type, String optionSetId, String referenceType, JSONB translations, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, Boolean isMeasure, String aggregationType, Boolean isDimension, JSONB propertiesMap) {
        super(DataElement.DATA_ELEMENT);

        setId(id);
        setUid(uid);
        setCode(code);
        setName(name);
        setShortName(shortName);
        setDescription(description);
        setType(type);
        setOptionSetId(optionSetId);
        setReferenceType(referenceType);
        setTranslations(translations);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setIsMeasure(isMeasure);
        setAggregationType(aggregationType);
        setIsDimension(isDimension);
        setPropertiesMap(propertiesMap);
        resetChangedOnNotNull();
    }
}
