/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.DataElementGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataElementGroupRecord extends UpdatableRecordImpl<DataElementGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.data_element_group.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.data_element_group.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.data_element_group.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.data_element_group.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.data_element_group.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.data_element_group.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.data_element_group.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.data_element_group.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.data_element_group.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.data_element_group.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>public.data_element_group.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.data_element_group.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.data_element_group.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.data_element_group.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.data_element_group.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.data_element_group.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.data_element_group.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.data_element_group.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.data_element_group.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.data_element_group.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataElementGroupRecord
     */
    public DataElementGroupRecord() {
        super(DataElementGroup.DATA_ELEMENT_GROUP);
    }

    /**
     * Create a detached, initialised DataElementGroupRecord
     */
    public DataElementGroupRecord(String id, String uid, String code, String name, JSONB translations, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, JSONB propertiesMap) {
        super(DataElementGroup.DATA_ELEMENT_GROUP);

        setId(id);
        setUid(uid);
        setCode(code);
        setName(name);
        setTranslations(translations);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setPropertiesMap(propertiesMap);
        resetChangedOnNotNull();
    }
}
