/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.DataSubmission;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataSubmissionRecord extends UpdatableRecordImpl<DataSubmissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.data_submission.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.data_submission.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.data_submission.serial_number</code>.
     */
    public void setSerialNumber(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.data_submission.serial_number</code>.
     */
    public Long getSerialNumber() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.data_submission.uid</code>.
     */
    public void setUid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.data_submission.uid</code>.
     */
    public String getUid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.data_submission.template_uid</code>.
     */
    public void setTemplateUid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.data_submission.template_uid</code>.
     */
    public String getTemplateUid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.data_submission.template_version_uid</code>.
     */
    public void setTemplateVersionUid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.data_submission.template_version_uid</code>.
     */
    public String getTemplateVersionUid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.data_submission.template_version_no</code>.
     */
    public void setTemplateVersionNo(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.data_submission.template_version_no</code>.
     */
    public Integer getTemplateVersionNo() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.data_submission.submission_version</code>.
     */
    public void setSubmissionVersion(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.data_submission.submission_version</code>.
     */
    public Integer getSubmissionVersion() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.data_submission.assignment_uid</code>.
     */
    public void setAssignmentUid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.data_submission.assignment_uid</code>.
     */
    public String getAssignmentUid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.data_submission.activity_uid</code>.
     */
    public void setActivityUid(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.data_submission.activity_uid</code>.
     */
    public String getActivityUid() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.data_submission.team_uid</code>.
     */
    public void setTeamUid(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.data_submission.team_uid</code>.
     */
    public String getTeamUid() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.data_submission.team_code</code>.
     */
    public void setTeamCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.data_submission.team_code</code>.
     */
    public String getTeamCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.data_submission.org_unit_uid</code>.
     */
    public void setOrgUnitUid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.data_submission.org_unit_uid</code>.
     */
    public String getOrgUnitUid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.data_submission.org_unit_code</code>.
     */
    public void setOrgUnitCode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.data_submission.org_unit_code</code>.
     */
    public String getOrgUnitCode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.data_submission.org_unit_name</code>.
     */
    public void setOrgUnitName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.data_submission.org_unit_name</code>.
     */
    public String getOrgUnitName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.data_submission.status</code>.
     */
    public void setStatus(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.data_submission.status</code>.
     */
    public String getStatus() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.data_submission.start_entry_time</code>.
     */
    public void setStartEntryTime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.data_submission.start_entry_time</code>.
     */
    public LocalDateTime getStartEntryTime() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>public.data_submission.finished_entry_time</code>.
     */
    public void setFinishedEntryTime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.data_submission.finished_entry_time</code>.
     */
    public LocalDateTime getFinishedEntryTime() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>public.data_submission.form_data</code>.
     */
    public void setFormData(JSONB value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.data_submission.form_data</code>.
     */
    public JSONB getFormData() {
        return (JSONB) get(17);
    }

    /**
     * Setter for <code>public.data_submission.lock_version</code>.
     */
    public void setLockVersion(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.data_submission.lock_version</code>.
     */
    public Long getLockVersion() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.data_submission.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.data_submission.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.data_submission.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.data_submission.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>public.data_submission.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.data_submission.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.data_submission.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.data_submission.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(22);
    }

    /**
     * Setter for <code>public.data_submission.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.data_submission.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(23);
    }

    /**
     * Setter for <code>public.data_submission.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.data_submission.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>public.data_submission.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.data_submission.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(25);
    }

    /**
     * Setter for <code>public.data_submission.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.data_submission.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataSubmissionRecord
     */
    public DataSubmissionRecord() {
        super(DataSubmission.DATA_SUBMISSION);
    }

    /**
     * Create a detached, initialised DataSubmissionRecord
     */
    public DataSubmissionRecord(String id, Long serialNumber, String uid, String templateUid, String templateVersionUid, Integer templateVersionNo, Integer submissionVersion, String assignmentUid, String activityUid, String teamUid, String teamCode, String orgUnitUid, String orgUnitCode, String orgUnitName, String status, LocalDateTime startEntryTime, LocalDateTime finishedEntryTime, JSONB formData, Long lockVersion, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, JSONB translations, Boolean deleted, LocalDateTime deletedAt, JSONB propertiesMap) {
        super(DataSubmission.DATA_SUBMISSION);

        setId(id);
        setSerialNumber(serialNumber);
        setUid(uid);
        setTemplateUid(templateUid);
        setTemplateVersionUid(templateVersionUid);
        setTemplateVersionNo(templateVersionNo);
        setSubmissionVersion(submissionVersion);
        setAssignmentUid(assignmentUid);
        setActivityUid(activityUid);
        setTeamUid(teamUid);
        setTeamCode(teamCode);
        setOrgUnitUid(orgUnitUid);
        setOrgUnitCode(orgUnitCode);
        setOrgUnitName(orgUnitName);
        setStatus(status);
        setStartEntryTime(startEntryTime);
        setFinishedEntryTime(finishedEntryTime);
        setFormData(formData);
        setLockVersion(lockVersion);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setTranslations(translations);
        setDeleted(deleted);
        setDeletedAt(deletedAt);
        setPropertiesMap(propertiesMap);
        resetChangedOnNotNull();
    }
}
