/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.MigrationErrors;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MigrationErrorsRecord extends UpdatableRecordImpl<MigrationErrorsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.migration_errors.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.migration_errors.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.migration_errors.source_id</code>.
     */
    public void setSourceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.migration_errors.source_id</code>.
     */
    public String getSourceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.migration_errors.submission_uid</code>.
     */
    public void setSubmissionUid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.migration_errors.submission_uid</code>.
     */
    public String getSubmissionUid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.migration_errors.stage</code>.
     */
    public void setStage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.migration_errors.stage</code>.
     */
    public String getStage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.migration_errors.error_class</code>.
     */
    public void setErrorClass(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.migration_errors.error_class</code>.
     */
    public String getErrorClass() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.migration_errors.error_message</code>.
     */
    public void setErrorMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.migration_errors.error_message</code>.
     */
    public String getErrorMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.migration_errors.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.migration_errors.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.migration_errors.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.migration_errors.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MigrationErrorsRecord
     */
    public MigrationErrorsRecord() {
        super(MigrationErrors.MIGRATION_ERRORS);
    }

    /**
     * Create a detached, initialised MigrationErrorsRecord
     */
    public MigrationErrorsRecord(Long id, String sourceId, String submissionUid, String stage, String errorClass, String errorMessage, JSONB payload, LocalDateTime createdAt) {
        super(MigrationErrors.MIGRATION_ERRORS);

        setId(id);
        setSourceId(sourceId);
        setSubmissionUid(submissionUid);
        setStage(stage);
        setErrorClass(errorClass);
        setErrorMessage(errorMessage);
        setPayload(payload);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
