/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.OptionGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OptionGroupRecord extends UpdatableRecordImpl<OptionGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.option_group.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.option_group.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.option_group.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.option_group.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>public.option_group.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.option_group.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.option_group.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.option_group.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.option_group.shortname</code>.
     */
    public void setShortname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.option_group.shortname</code>.
     */
    public String getShortname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.option_group.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.option_group.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.option_group.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.option_group.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.option_group.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.option_group.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.option_group.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.option_group.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.option_group.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.option_group.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.option_group.option_set_id</code>.
     */
    public void setOptionSetId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.option_group.option_set_id</code>.
     */
    public String getOptionSetId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.option_group.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.option_group.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OptionGroupRecord
     */
    public OptionGroupRecord() {
        super(OptionGroup.OPTION_GROUP);
    }

    /**
     * Create a detached, initialised OptionGroupRecord
     */
    public OptionGroupRecord(String id, JSONB translations, String code, String name, String shortname, String description, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, String optionSetId, JSONB propertiesMap) {
        super(OptionGroup.OPTION_GROUP);

        setId(id);
        setTranslations(translations);
        setCode(code);
        setName(name);
        setShortname(shortname);
        setDescription(description);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setOptionSetId(optionSetId);
        setPropertiesMap(propertiesMap);
        resetChangedOnNotNull();
    }
}
