/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.OptionGroupset_OptionGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OptionGroupset_OptionGroupRecord extends UpdatableRecordImpl<OptionGroupset_OptionGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.option_groupset__option_group.groupset_id</code>.
     */
    public void setGroupsetId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.option_groupset__option_group.groupset_id</code>.
     */
    public String getGroupsetId() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>public.option_groupset__option_group.option_group_id</code>.
     */
    public void setOptionGroupId(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.option_groupset__option_group.option_group_id</code>.
     */
    public String getOptionGroupId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.option_groupset__option_group.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.option_groupset__option_group.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OptionGroupset_OptionGroupRecord
     */
    public OptionGroupset_OptionGroupRecord() {
        super(OptionGroupset_OptionGroup.OPTION_GROUPSET__OPTION_GROUP);
    }

    /**
     * Create a detached, initialised OptionGroupset_OptionGroupRecord
     */
    public OptionGroupset_OptionGroupRecord(String groupsetId, String optionGroupId, Integer sortOrder) {
        super(OptionGroupset_OptionGroup.OPTION_GROUPSET__OPTION_GROUP);

        setGroupsetId(groupsetId);
        setOptionGroupId(optionGroupId);
        setSortOrder(sortOrder);
        resetChangedOnNotNull();
    }
}
