/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.OptionValue;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OptionValueRecord extends UpdatableRecordImpl<OptionValueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.option_value.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.option_value.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.option_value.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.option_value.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.option_value.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.option_value.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.option_value.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.option_value.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.option_value.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.option_value.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>public.option_value.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.option_value.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.option_value.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.option_value.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.option_value.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.option_value.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.option_value.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.option_value.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.option_value.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.option_value.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.option_value.option_set_id</code>.
     */
    public void setOptionSetId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.option_value.option_set_id</code>.
     */
    public String getOptionSetId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.option_value.uid</code>.
     */
    public void setUid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.option_value.uid</code>.
     */
    public String getUid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.option_value.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.option_value.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OptionValueRecord
     */
    public OptionValueRecord() {
        super(OptionValue.OPTION_VALUE);
    }

    /**
     * Create a detached, initialised OptionValueRecord
     */
    public OptionValueRecord(String id, String code, String name, String description, JSONB translations, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, Integer sortOrder, String optionSetId, String uid, JSONB propertiesMap) {
        super(OptionValue.OPTION_VALUE);

        setId(id);
        setCode(code);
        setName(name);
        setDescription(description);
        setTranslations(translations);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setSortOrder(sortOrder);
        setOptionSetId(optionSetId);
        setUid(uid);
        setPropertiesMap(propertiesMap);
        resetChangedOnNotNull();
    }
}
