/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.OrgUnitHierarchy;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgUnitHierarchyRecord extends UpdatableRecordImpl<OrgUnitHierarchyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.org_unit_hierarchy.ancestor_id</code>.
     */
    public void setAncestorId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.org_unit_hierarchy.ancestor_id</code>.
     */
    public String getAncestorId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.org_unit_hierarchy.descendant_id</code>.
     */
    public void setDescendantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.org_unit_hierarchy.descendant_id</code>.
     */
    public String getDescendantId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.org_unit_hierarchy.level_diff</code>.
     */
    public void setLevelDiff(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.org_unit_hierarchy.level_diff</code>.
     */
    public Integer getLevelDiff() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrgUnitHierarchyRecord
     */
    public OrgUnitHierarchyRecord() {
        super(OrgUnitHierarchy.ORG_UNIT_HIERARCHY);
    }

    /**
     * Create a detached, initialised OrgUnitHierarchyRecord
     */
    public OrgUnitHierarchyRecord(String ancestorId, String descendantId, Integer levelDiff) {
        super(OrgUnitHierarchy.ORG_UNIT_HIERARCHY);

        setAncestorId(ancestorId);
        setDescendantId(descendantId);
        setLevelDiff(levelDiff);
        resetChangedOnNotNull();
    }
}
