/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.OrgUnitGroupsetOrgUnitGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgUnitGroupsetOrgUnitGroupRecord extends UpdatableRecordImpl<OrgUnitGroupsetOrgUnitGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.org_unit_groupset_org_unit_group.groupset_id</code>.
     */
    public void setGroupsetId(String value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.org_unit_groupset_org_unit_group.groupset_id</code>.
     */
    public String getGroupsetId() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>public.org_unit_groupset_org_unit_group.org_unit_group_id</code>.
     */
    public void setOrgUnitGroupId(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.org_unit_groupset_org_unit_group.org_unit_group_id</code>.
     */
    public String getOrgUnitGroupId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrgUnitGroupsetOrgUnitGroupRecord
     */
    public OrgUnitGroupsetOrgUnitGroupRecord() {
        super(OrgUnitGroupsetOrgUnitGroup.ORG_UNIT_GROUPSET_ORG_UNIT_GROUP);
    }

    /**
     * Create a detached, initialised OrgUnitGroupsetOrgUnitGroupRecord
     */
    public OrgUnitGroupsetOrgUnitGroupRecord(String groupsetId, String orgUnitGroupId) {
        super(OrgUnitGroupsetOrgUnitGroup.ORG_UNIT_GROUPSET_ORG_UNIT_GROUP);

        setGroupsetId(groupsetId);
        setOrgUnitGroupId(orgUnitGroupId);
        resetChangedOnNotNull();
    }
}
