/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.JSONB;
import org.jooq.impl.TableRecordImpl;
import org.nmcpye.datarun.jooq.tables.PivotGridFacts;

import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PivotGridFactsRecord extends TableRecordImpl<PivotGridFactsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pivot_grid_facts.value_id</code>.
     */
    public void setValueId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.value_id</code>.
     */
    public Long getValueId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.submission_uid</code>.
     */
    public void setSubmissionUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.submission_uid</code>.
     */
    public String getSubmissionUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.form_template_uid</code>.
     */
    public void setFormTemplateUid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.form_template_uid</code>.
     */
    public String getFormTemplateUid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.form_version_uid</code>.
     */
    public void setFormVersionUid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.form_version_uid</code>.
     */
    public String getFormVersionUid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.te_uid</code>.
     */
    public void setEtcUid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.te_uid</code>.
     */
    public String getEtcUid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.template_repeat_path</code>.
     */
    public void setTemplateRepeatPath(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.template_repeat_path</code>.
     */
    public String getTemplateRepeatPath() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.template_name_path</code>.
     */
    public void setTemplateNamePath(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.template_name_path</code>.
     */
    public String getTemplateNamePath() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.template_id_path</code>.
     */
    public void setTemplateIdPath(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.template_id_path</code>.
     */
    public String getTemplateIdPath() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.category_element_uid</code>.
     */
    public void setCategoryElementUid(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.category_element_uid</code>.
     */
    public String getCategoryElementUid() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.repeat_instance_id</code>.
     */
    public void setRepeatInstanceId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.repeat_instance_id</code>.
     */
    public String getRepeatInstanceId() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>public.pivot_grid_facts.parent_repeat_instance_id</code>.
     */
    public void setParentRepeatInstanceId(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>public.pivot_grid_facts.parent_repeat_instance_id</code>.
     */
    public String getParentRepeatInstanceId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.repeat_path</code>.
     */
    public void setRepeatPath(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.repeat_path</code>.
     */
    public String getRepeatPath() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.repeat_section_label</code>.
     */
    public void setRepeatSectionLabel(JSONB value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.repeat_section_label</code>.
     */
    public JSONB getRepeatSectionLabel() {
        return (JSONB) get(12);
    }

    /**
     * Setter for
     * <code>public.pivot_grid_facts.parent_repeat_section_label</code>.
     */
    public void setParentRepeatSectionLabel(JSONB value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>public.pivot_grid_facts.parent_repeat_section_label</code>.
     */
    public JSONB getParentRepeatSectionLabel() {
        return (JSONB) get(13);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.assignment_uid</code>.
     */
    public void setAssignmentUid(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.assignment_uid</code>.
     */
    public String getAssignmentUid() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.team_uid</code>.
     */
    public void setTeamUid(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.team_uid</code>.
     */
    public String getTeamUid() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.team_code</code>.
     */
    public void setTeamCode(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.team_code</code>.
     */
    public String getTeamCode() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.org_unit_uid</code>.
     */
    public void setOrgUnitUid(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.org_unit_uid</code>.
     */
    public String getOrgUnitUid() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.org_unit_name</code>.
     */
    public void setOrgUnitName(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.org_unit_name</code>.
     */
    public String getOrgUnitName() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.org_unit_code</code>.
     */
    public void setOrgUnitCode(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.org_unit_code</code>.
     */
    public String getOrgUnitCode() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.activity_uid</code>.
     */
    public void setActivityUid(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.activity_uid</code>.
     */
    public String getActivityUid() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.activity_name</code>.
     */
    public void setActivityName(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.activity_name</code>.
     */
    public String getActivityName() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.submission_completed_at</code>.
     */
    public void setSubmissionCompletedAt(LocalDateTime value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.submission_completed_at</code>.
     */
    public LocalDateTime getSubmissionCompletedAt() {
        return (LocalDateTime) get(22);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.child_category_uid</code>.
     */
    public void setChildCategoryUid(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.child_category_uid</code>.
     */
    public String getChildCategoryUid() {
        return (String) get(23);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.parent_category_uid</code>.
     */
    public void setParentCategoryUid(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.parent_category_uid</code>.
     */
    public String getParentCategoryUid() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.child_category_kind</code>.
     */
    public void setChildCategoryKind(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.child_category_kind</code>.
     */
    public String getChildCategoryKind() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.parent_category_kind</code>.
     */
    public void setParentCategoryKind(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.parent_category_kind</code>.
     */
    public String getParentCategoryKind() {
        return (String) get(26);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.display_label</code>.
     */
    public void setDisplayLabel(JSONB value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.display_label</code>.
     */
    public JSONB getDisplayLabel() {
        return (JSONB) get(27);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.category_id</code>.
     */
    public void setCategoryId(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.category_id</code>.
     */
    public String getCategoryId() {
        return (String) get(28);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.de_uid</code>.
     */
    public void setDeUid(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.de_uid</code>.
     */
    public String getDeUid() {
        return (String) get(29);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.de_name</code>.
     */
    public void setDeName(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.de_name</code>.
     */
    public String getDeName() {
        return (String) get(30);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.de_value_type</code>.
     */
    public void setDeValueType(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.de_value_type</code>.
     */
    public String getDeValueType() {
        return (String) get(31);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.de_option_set_uid</code>.
     */
    public void setDeOptionSetUid(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.de_option_set_uid</code>.
     */
    public String getDeOptionSetUid() {
        return (String) get(32);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.option_uid</code>.
     */
    public void setOptionUid(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.option_uid</code>.
     */
    public String getOptionUid() {
        return (String) get(33);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.option_value_uid</code>.
     */
    public void setOptionValueUid(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.option_value_uid</code>.
     */
    public String getOptionValueUid() {
        return (String) get(34);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.option_name</code>.
     */
    public void setOptionName(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.option_name</code>.
     */
    public String getOptionName() {
        return (String) get(35);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.option_code</code>.
     */
    public void setOptionCode(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.option_code</code>.
     */
    public String getOptionCode() {
        return (String) get(36);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.child_category_name</code>.
     */
    public void setChildCategoryName(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.child_category_name</code>.
     */
    public String getChildCategoryName() {
        return (String) get(37);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.parent_category_name</code>.
     */
    public void setParentCategoryName(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.parent_category_name</code>.
     */
    public String getParentCategoryName() {
        return (String) get(38);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.value_num</code>.
     */
    public void setValueNum(BigDecimal value) {
        set(39, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.value_num</code>.
     */
    public BigDecimal getValueNum() {
        return (BigDecimal) get(39);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.value_text</code>.
     */
    public void setValueText(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.value_text</code>.
     */
    public String getValueText() {
        return (String) get(40);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.value_bool</code>.
     */
    public void setValueBool(Boolean value) {
        set(41, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.value_bool</code>.
     */
    public Boolean getValueBool() {
        return (Boolean) get(41);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.value_ts</code>.
     */
    public void setValueTs(LocalDateTime value) {
        set(42, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.value_ts</code>.
     */
    public LocalDateTime getValueTs() {
        return (LocalDateTime) get(42);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.value_ref_uid</code>.
     */
    public void setValueRefUid(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.value_ref_uid</code>.
     */
    public String getValueRefUid() {
        return (String) get(43);
    }

    /**
     * Setter for <code>public.pivot_grid_facts.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(44, value);
    }

    /**
     * Getter for <code>public.pivot_grid_facts.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(44);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PivotGridFactsRecord
     */
    public PivotGridFactsRecord() {
        super(PivotGridFacts.PIVOT_GRID_FACTS);
    }

    /**
     * Create a detached, initialised PivotGridFactsRecord
     */
    public PivotGridFactsRecord(Long valueId, String submissionUid, String formTemplateUid, String formVersionUid, String etcUid, String templateRepeatPath, String templateNamePath, String templateIdPath, String categoryElementUid, String repeatInstanceId, String parentRepeatInstanceId, String repeatPath, JSONB repeatSectionLabel, JSONB parentRepeatSectionLabel, String assignmentUid, String teamUid, String teamCode, String orgUnitUid, String orgUnitName, String orgUnitCode, String activityUid, String activityName, LocalDateTime submissionCompletedAt, String childCategoryUid, String parentCategoryUid, String childCategoryKind, String parentCategoryKind, JSONB displayLabel, String categoryId, String deUid, String deName, String deValueType, String deOptionSetUid, String optionUid, String optionValueUid, String optionName, String optionCode, String childCategoryName, String parentCategoryName, BigDecimal valueNum, String valueText, Boolean valueBool, LocalDateTime valueTs, String valueRefUid, LocalDateTime deletedAt) {
        super(PivotGridFacts.PIVOT_GRID_FACTS);

        setValueId(valueId);
        setSubmissionUid(submissionUid);
        setFormTemplateUid(formTemplateUid);
        setFormVersionUid(formVersionUid);
        setEtcUid(etcUid);
        setTemplateRepeatPath(templateRepeatPath);
        setTemplateNamePath(templateNamePath);
        setTemplateIdPath(templateIdPath);
        setCategoryElementUid(categoryElementUid);
        setRepeatInstanceId(repeatInstanceId);
        setParentRepeatInstanceId(parentRepeatInstanceId);
        setRepeatPath(repeatPath);
        setRepeatSectionLabel(repeatSectionLabel);
        setParentRepeatSectionLabel(parentRepeatSectionLabel);
        setAssignmentUid(assignmentUid);
        setTeamUid(teamUid);
        setTeamCode(teamCode);
        setOrgUnitUid(orgUnitUid);
        setOrgUnitName(orgUnitName);
        setOrgUnitCode(orgUnitCode);
        setActivityUid(activityUid);
        setActivityName(activityName);
        setSubmissionCompletedAt(submissionCompletedAt);
        setChildCategoryUid(childCategoryUid);
        setParentCategoryUid(parentCategoryUid);
        setChildCategoryKind(childCategoryKind);
        setParentCategoryKind(parentCategoryKind);
        setDisplayLabel(displayLabel);
        setCategoryId(categoryId);
        setDeUid(deUid);
        setDeName(deName);
        setDeValueType(deValueType);
        setDeOptionSetUid(deOptionSetUid);
        setOptionUid(optionUid);
        setOptionValueUid(optionValueUid);
        setOptionName(optionName);
        setOptionCode(optionCode);
        setChildCategoryName(childCategoryName);
        setParentCategoryName(parentCategoryName);
        setValueNum(valueNum);
        setValueText(valueText);
        setValueBool(valueBool);
        setValueTs(valueTs);
        setValueRefUid(valueRefUid);
        setDeletedAt(deletedAt);
        resetChangedOnNotNull();
    }
}
