/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.RefreshToken;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefreshTokenRecord extends UpdatableRecordImpl<RefreshTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.refresh_token.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.refresh_token.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.refresh_token.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.refresh_token.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.refresh_token.expiry_date</code>.
     */
    public void setExpiryDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.refresh_token.expiry_date</code>.
     */
    public LocalDateTime getExpiryDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.refresh_token.user_id</code>.
     */
    public void setUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.refresh_token.user_id</code>.
     */
    public String getUserId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefreshTokenRecord
     */
    public RefreshTokenRecord() {
        super(RefreshToken.REFRESH_TOKEN);
    }

    /**
     * Create a detached, initialised RefreshTokenRecord
     */
    public RefreshTokenRecord(String id, String token, LocalDateTime expiryDate, String userId) {
        super(RefreshToken.REFRESH_TOKEN);

        setId(id);
        setToken(token);
        setExpiryDate(expiryDate);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
