/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.RepeatInstance;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RepeatInstanceRecord extends UpdatableRecordImpl<RepeatInstanceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.repeat_instance.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.repeat_instance.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.repeat_instance.semantic_path</code>.
     */
    public void setSemanticPath(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.repeat_instance.semantic_path</code>.
     */
    public String getSemanticPath() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.repeat_instance.parent_repeat_instance_id</code>.
     */
    public void setParentRepeatInstanceId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.repeat_instance.parent_repeat_instance_id</code>.
     */
    public String getParentRepeatInstanceId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.repeat_instance.repeat_section_label</code>.
     */
    public void setRepeatSectionLabel(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.repeat_instance.repeat_section_label</code>.
     */
    public JSONB getRepeatSectionLabel() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.repeat_instance.submission_uid</code>.
     */
    public void setSubmissionUid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.repeat_instance.submission_uid</code>.
     */
    public String getSubmissionUid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.repeat_instance.category_kind</code>.
     */
    public void setCategoryKind(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.repeat_instance.category_kind</code>.
     */
    public String getCategoryKind() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.repeat_instance.category_uid</code>.
     */
    public void setCategoryUid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.repeat_instance.category_uid</code>.
     */
    public String getCategoryUid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.repeat_instance.category_name</code>.
     */
    public void setCategoryName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.repeat_instance.category_name</code>.
     */
    public String getCategoryName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.repeat_instance.category_label</code>.
     */
    public void setCategoryLabel(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.repeat_instance.category_label</code>.
     */
    public JSONB getCategoryLabel() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.repeat_instance.repeat_path</code>.
     */
    public void setRepeatPath(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.repeat_instance.repeat_path</code>.
     */
    public String getRepeatPath() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.repeat_instance.repeat_index</code>.
     */
    public void setRepeatIndex(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.repeat_instance.repeat_index</code>.
     */
    public Long getRepeatIndex() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.repeat_instance.client_updated_at</code>.
     */
    public void setClientUpdatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.repeat_instance.client_updated_at</code>.
     */
    public LocalDateTime getClientUpdatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.repeat_instance.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.repeat_instance.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.repeat_instance.submission_completed_at</code>.
     */
    public void setSubmissionCompletedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.repeat_instance.submission_completed_at</code>.
     */
    public LocalDateTime getSubmissionCompletedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.repeat_instance.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.repeat_instance.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>public.repeat_instance.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.repeat_instance.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>public.repeat_instance.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.repeat_instance.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.repeat_instance.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.repeat_instance.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RepeatInstanceRecord
     */
    public RepeatInstanceRecord() {
        super(RepeatInstance.REPEAT_INSTANCE);
    }

    /**
     * Create a detached, initialised RepeatInstanceRecord
     */
    public RepeatInstanceRecord(String id, String semanticPath, String parentRepeatInstanceId, JSONB repeatSectionLabel, String submissionUid, String categoryKind, String categoryUid, String categoryName, JSONB categoryLabel, String repeatPath, Long repeatIndex, LocalDateTime clientUpdatedAt, LocalDateTime deletedAt, LocalDateTime submissionCompletedAt, LocalDateTime createdDate, LocalDateTime lastModifiedDate, String lastModifiedBy, String createdBy) {
        super(RepeatInstance.REPEAT_INSTANCE);

        setId(id);
        setSemanticPath(semanticPath);
        setParentRepeatInstanceId(parentRepeatInstanceId);
        setRepeatSectionLabel(repeatSectionLabel);
        setSubmissionUid(submissionUid);
        setCategoryKind(categoryKind);
        setCategoryUid(categoryUid);
        setCategoryName(categoryName);
        setCategoryLabel(categoryLabel);
        setRepeatPath(repeatPath);
        setRepeatIndex(repeatIndex);
        setClientUpdatedAt(clientUpdatedAt);
        setDeletedAt(deletedAt);
        setSubmissionCompletedAt(submissionCompletedAt);
        setCreatedDate(createdDate);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
