/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.Role;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.role.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.role.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.role.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.role.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>public.role.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.role.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.role.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.role.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.role.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.role.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.role.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.role.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.role.uid</code>.
     */
    public void setUid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.role.uid</code>.
     */
    public String getUid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.role.code</code>.
     */
    public void setCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.role.code</code>.
     */
    public String getCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.role.name</code>.
     */
    public void setName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.role.name</code>.
     */
    public String getName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.role.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.role.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(String id, JSONB translations, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, String uid, String code, String name, JSONB propertiesMap) {
        super(Role.ROLE);

        setId(id);
        setTranslations(translations);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setUid(uid);
        setCode(code);
        setName(name);
        setPropertiesMap(propertiesMap);
        resetChangedOnNotNull();
    }
}
