/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;
import org.nmcpye.datarun.jooq.tables.RolePrivilegeMembers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePrivilegeMembersRecord extends TableRecordImpl<RolePrivilegeMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.role_privilege_members.privilege_id</code>.
     */
    public void setPrivilegeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.role_privilege_members.privilege_id</code>.
     */
    public String getPrivilegeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.role_privilege_members.role_id</code>.
     */
    public void setRoleId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.role_privilege_members.role_id</code>.
     */
    public String getRoleId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolePrivilegeMembersRecord
     */
    public RolePrivilegeMembersRecord() {
        super(RolePrivilegeMembers.ROLE_PRIVILEGE_MEMBERS);
    }

    /**
     * Create a detached, initialised RolePrivilegeMembersRecord
     */
    public RolePrivilegeMembersRecord(String privilegeId, String roleId) {
        super(RolePrivilegeMembers.ROLE_PRIVILEGE_MEMBERS);

        setPrivilegeId(privilegeId);
        setRoleId(roleId);
        resetChangedOnNotNull();
    }
}
