/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.TeamManagedTeams;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamManagedTeamsRecord extends UpdatableRecordImpl<TeamManagedTeamsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.team_managed_teams.managed_team_id</code>.
     */
    public void setManagedTeamId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.team_managed_teams.managed_team_id</code>.
     */
    public String getManagedTeamId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.team_managed_teams.team_id</code>.
     */
    public void setTeamId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.team_managed_teams.team_id</code>.
     */
    public String getTeamId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamManagedTeamsRecord
     */
    public TeamManagedTeamsRecord() {
        super(TeamManagedTeams.TEAM_MANAGED_TEAMS);
    }

    /**
     * Create a detached, initialised TeamManagedTeamsRecord
     */
    public TeamManagedTeamsRecord(String managedTeamId, String teamId) {
        super(TeamManagedTeams.TEAM_MANAGED_TEAMS);

        setManagedTeamId(managedTeamId);
        setTeamId(teamId);
        resetChangedOnNotNull();
    }
}
