/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.tables.UserGroupManagedGroups;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupManagedGroupsRecord extends UpdatableRecordImpl<UserGroupManagedGroupsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.user_group_managed_groups.managed_group_id</code>.
     */
    public void setManagedGroupId(String value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.user_group_managed_groups.managed_group_id</code>.
     */
    public String getManagedGroupId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_group_managed_groups.user_group_id</code>.
     */
    public void setUserGroupId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_group_managed_groups.user_group_id</code>.
     */
    public String getUserGroupId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserGroupManagedGroupsRecord
     */
    public UserGroupManagedGroupsRecord() {
        super(UserGroupManagedGroups.USER_GROUP_MANAGED_GROUPS);
    }

    /**
     * Create a detached, initialised UserGroupManagedGroupsRecord
     */
    public UserGroupManagedGroupsRecord(String managedGroupId, String userGroupId) {
        super(UserGroupManagedGroups.USER_GROUP_MANAGED_GROUPS);

        setManagedGroupId(managedGroupId);
        setUserGroupId(userGroupId);
        resetChangedOnNotNull();
    }
}
