package org.nmcpye.datarun.drun.postgres.domain.enumeration;

public enum FormPermission {
    VIEW_FORM_TEMPLATE,
    EDIT_FORM_TEMPLATE,
    VIEW_SUBMISSIONS,
    ADD_SUBMISSIONS,
    EDIT_SUBMISSIONS,
    EDIT_SUBMISSIONS_FROM_USERS,
    EDIT_SUBMISSIONS_CONDITION,
    APPROVE_SUBMISSIONS,
    APPROVE_SUBMISSIONS_CONDITION,
    DELETE_SUBMISSIONS,
    DELETE_SUBMISSIONS_FROM_USERS,
    DELETE_SUBMISSIONS_CONDITION
}
