/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Indexes;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.UserAllowedPartyRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAllowedParty extends TableImpl<UserAllowedPartyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_allowed_party</code>
     */
    public static final UserAllowedParty USER_ALLOWED_PARTY = new UserAllowedParty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAllowedPartyRecord> getRecordType() {
        return UserAllowedPartyRecord.class;
    }

    /**
     * The column <code>public.user_allowed_party.user_id</code>.
     */
    public final TableField<UserAllowedPartyRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.user_allowed_party.party_id</code>.
     */
    public final TableField<UserAllowedPartyRecord, UUID> PARTY_ID = createField(DSL.name("party_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.user_allowed_party.permission_mask</code>.
     */
    public final TableField<UserAllowedPartyRecord, Integer> PERMISSION_MASK = createField(DSL.name("permission_mask"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.user_allowed_party.provenance</code>.
     */
    public final TableField<UserAllowedPartyRecord, JSONB> PROVENANCE = createField(DSL.name("provenance"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.user_allowed_party.last_updated</code>.
     */
    public final TableField<UserAllowedPartyRecord, LocalDateTime> LAST_UPDATED = createField(DSL.name("last_updated"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private UserAllowedParty(Name alias, Table<UserAllowedPartyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserAllowedParty(Name alias, Table<UserAllowedPartyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_allowed_party</code> table reference
     */
    public UserAllowedParty(String alias) {
        this(DSL.name(alias), USER_ALLOWED_PARTY);
    }

    /**
     * Create an aliased <code>public.user_allowed_party</code> table reference
     */
    public UserAllowedParty(Name alias) {
        this(alias, USER_ALLOWED_PARTY);
    }

    /**
     * Create a <code>public.user_allowed_party</code> table reference
     */
    public UserAllowedParty() {
        this(DSL.name("user_allowed_party"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_UAP_PARTY, Indexes.IDX_UAP_USER);
    }

    @Override
    public UniqueKey<UserAllowedPartyRecord> getPrimaryKey() {
        return Keys.PK_USER_ALLOWED_PARTY;
    }

    @Override
    public UserAllowedParty as(String alias) {
        return new UserAllowedParty(DSL.name(alias), this);
    }

    @Override
    public UserAllowedParty as(Name alias) {
        return new UserAllowedParty(alias, this);
    }

    @Override
    public UserAllowedParty as(Table<?> alias) {
        return new UserAllowedParty(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAllowedParty rename(String name) {
        return new UserAllowedParty(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAllowedParty rename(Name name) {
        return new UserAllowedParty(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAllowedParty rename(Table<?> name) {
        return new UserAllowedParty(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAllowedParty where(Condition condition) {
        return new UserAllowedParty(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAllowedParty where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAllowedParty where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAllowedParty where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAllowedParty where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAllowedParty where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAllowedParty where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAllowedParty where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAllowedParty whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAllowedParty whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
